'use strict';
// Tests for the App Store launch switch (2026-09-25 founder decision):
// index.html's Component class gains an APP_STORE_URL config field, next to
// WAITLIST_ENDPOINT, that flips the home page from "join the waitlist" to
// "download on the App Store" once set: the nav link, hero button and
// closing CTA become pill-shaped "Download app" links carrying an inline
// Apple mark. The same build-time APP_STORE_URL constant also drives the
// shared mobile drawer (build/assemble.py's drawer()). See README.md, "App
// Store launch switch".
//
//     npm test          (or: node --test "test/*.test.js")
//
// index.html is generated by build/assemble.py (see build/check.py's own
// "unfilled build placeholder" rule) and is not hand-edited, so these tests
// read the committed file the same way build/check.py does.
//
// Three complementary techniques evaluate the feature in both states without
// a browser:
//
//   1. The Component class is a plain, DOM-free-at-render JS class (its
//      renderVals() touches no DOM), so it is extracted from its
//      <script type="text/x-dc" data-dc-script> block and evaluated the same
//      way the page's own runtime does (assets/app.*.js's evalDcLogic:
//      new Function('DCLogic','StreamableLogic','React', src + ...)),
//      mirroring how gmail-pair.test.js and payout-return.test.js vm-execute
//      this page's plain <script> blocks. This gives the exact computed
//      values (button text, which of pick0..pick4 are live handlers, the
//      link href/label) for a given APP_STORE_URL.
//   2. A small, deliberately minimal re-implementation of this template
//      system's two primitives: {{ expr }} interpolation and
//      <sc-if value="{{ expr }}">...</sc-if> conditional blocks. It resolves
//      the static markup against those same computed values, so assertions
//      read like "what's on the page" rather than "what's in the template
//      source". It does not need sc-for (unused by the pieces under test).
//   3. The mobile drawer is different from techniques 1 and 2: it is static
//      markup baked once per build by build/assemble.py's drawer(), entirely
//      outside index.html's reactive template (no <sc-if>, no renderVals()),
//      so a single committed build can only ever show the branch that was
//      active when it was built. This repo's committed build was generated
//      with APP_STORE_URL empty, so the drawer's live branch cannot be
//      observed by reading any committed HTML file; the tests for it read
//      build/assemble.py's own source instead, the same way techniques 1 and
//      2 already treat index.html's source as ground truth for a build.
//   4. 2026-09-25 founder follow-up: how-it-works, faq, about, contact,
//      accountability-challenges, the blog hub and both articles each carry
//      their own copy of the same desktop nav pill and closing CTA block as
//      index.html and the drawer (build/assemble.py's
//      apply_content_app_store_switch(), applied to build/content-page.html,
//      build/article-page.html and build/blog-index.html), and four of them
//      also carry their own in-copy waitlist sentence (CONTENT_LIVE_COPY).
//      None of this is reactive, so exactly like technique 3, the live-state
//      markup cannot be observed from any committed HTML file; those tests
//      read build/assemble.py's source, while the default-state tests read
//      the real committed pages (this build's actual, current state).

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.join(__dirname, '..');
const APP_STORE_URL = 'https://apps.apple.com/app/id6802558635';

/** Escapes a string for safe use inside a RegExp built at runtime. */
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Matches the inline Apple logo mark (a single <path>, aria-hidden, sized in
 * em) shared by the three App Store buttons and the drawer link. Its viewBox
 * is a unique fingerprint on this page: index.html's only other <svg> (a
 * bundler thumbnail template, present regardless of mode) uses
 * viewBox="0 0 100 100".
 */
const APPLE_MARK_RE = /<svg aria-hidden="true" viewBox="0 0 384 512"[^>]*>[\s\S]*?<\/svg>/;

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// ------------------------------------------------------------- the harness

const scriptMatch = html.match(/<script type="text\/x-dc" data-dc-script[^>]*>([\s\S]*?)<\/script>/);
assert.ok(scriptMatch, 'index.html: could not find the <script type="text/x-dc" data-dc-script> block');
const componentSrc = scriptMatch[1];

class FakeLogic {
  constructor(props) { this.props = props || {}; this.state = {}; }
  setState(update) {
    const patch = typeof update === 'function' ? update(this.state) : update;
    Object.assign(this.state, patch);
  }
  forceUpdate() {}
  componentDidMount() {}
  componentDidUpdate() {}
  componentWillUnmount() {}
  renderVals() { return {}; }
}

// Mirrors assets/app.*.js's evalDcLogic() exactly (same three globals, same
// trailing expression), so this is the real evaluation path, not a guess at it.
const ComponentClass = new Function('DCLogic', 'StreamableLogic', 'React',
  componentSrc + '\n;return (typeof Component!=="undefined"&&Component)||undefined;'
)(FakeLogic, FakeLogic, {});
assert.equal(typeof ComponentClass, 'function', 'index.html: class Component extends DCLogic not found/evaluable');

/** renderVals() for a fresh instance with the given APP_STORE_URL ('' = default/off). */
function valsFor(appStoreUrl) {
  const c = new ComponentClass();
  c.APP_STORE_URL = appStoreUrl;
  return c.renderVals();
}

const DEFAULT_VALS = valsFor('');
const LIVE_VALS = valsFor(APP_STORE_URL);

// ---------------------------------------------------------- template micro-resolver

function resolveExpr(vals, expr) {
  expr = expr.trim();
  if (expr[0] === '!') return !resolveExpr(vals, expr.slice(1));
  if (expr === 'true') return true;
  if (expr === 'false') return false;
  return vals[expr];
}

/** Index of the </sc-if> that matches the <sc-if ...> whose '>' is at openEnd. */
function findMatchingClose(src, openEnd) {
  let depth = 1;
  let i = openEnd;
  for (;;) {
    const nextOpen = src.indexOf('<sc-if', i);
    const nextClose = src.indexOf('</sc-if>', i);
    if (nextClose === -1) throw new Error('unmatched <sc-if> in index.html');
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth++;
      i = src.indexOf('>', nextOpen) + 1;
    } else {
      depth--;
      if (depth === 0) return nextClose;
      i = nextClose + '</sc-if>'.length;
    }
  }
}

/**
 * Resolves {{ expr }} interpolation and nested <sc-if value="{{ expr }}">
 * blocks against `vals`, the same object the real runtime's renderVals()
 * produces. A function-valued expression (an event handler) renders as the
 * literal "fn" marker, present vs. absent being exactly what matters for the
 * plates' onClick/onKeyDown. Good enough for this page's own template
 * (sc-for is not used by anything under test, so it is left unhandled).
 */
function renderTemplate(src, vals) {
  let out = '';
  let i = 0;
  for (;;) {
    const nextTag = src.indexOf('<sc-if', i);
    if (nextTag === -1) { out += src.slice(i); break; }
    out += src.slice(i, nextTag);
    const tagEnd = src.indexOf('>', nextTag) + 1;
    const tagText = src.slice(nextTag, tagEnd);
    const exprMatch = tagText.match(/value="\{\{([^}]+)\}\}"/);
    const closeIdx = findMatchingClose(src, tagEnd);
    const inner = src.slice(tagEnd, closeIdx);
    const keep = exprMatch ? resolveExpr(vals, exprMatch[1]) : false;
    out += keep ? renderTemplate(inner, vals) : '';
    i = closeIdx + '</sc-if>'.length;
  }
  return out.replace(/\{\{\s*([^}]+?)\s*\}\}/g, (_, expr) => {
    const v = resolveExpr(vals, expr);
    if (v === undefined || v === null || v === false) return '';
    if (typeof v === 'function') return 'fn';
    return String(v);
  });
}

// Sanity-check the micro-resolver itself against a case with a known answer,
// before trusting it for the real assertions below.
test('sanity: the template micro-resolver keeps only the true sc-if branch and drops the other', () => {
  const t = '<sc-if value="{{ a }}">YES</sc-if><sc-if value="{{ !a }}">NO</sc-if><p>{{ b }}</p>';
  assert.equal(renderTemplate(t, { a: true, b: 'hi' }), 'YES<p>hi</p>');
  assert.equal(renderTemplate(t, { a: false, b: 'hi' }), 'NO<p>hi</p>');
});

const DEFAULT_HTML = renderTemplate(html, DEFAULT_VALS);
const LIVE_HTML = renderTemplate(html, LIVE_VALS);

/**
 * The Component class's own JS source (inside <script type="text/x-dc"
 * data-dc-script>) necessarily contains both 'JOIN THE WAITLIST' and
 * 'Download app' as string literals: renderVals() has to compute both
 * regardless of which one is live, since which mode is active
 * isn't known until a real instance's APP_STORE_URL is read. Likewise the
 * mobile nav-hide rule in <style> spells out the App Store URL so it can
 * match it without reading the JS constant (its own dedicated test below).
 * Neither is rendered markup, so whole-page "does this text appear on the
 * page" checks scope to everything outside <script>/<style> tags.
 */
function visibleMarkup(rendered) {
  return rendered.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<style[^>]*>[\s\S]*?<\/style>/g, '');
}

const DEFAULT_VISIBLE = visibleMarkup(DEFAULT_HTML);
const LIVE_VISIBLE = visibleMarkup(LIVE_HTML);

test('sanity: visibleMarkup strips embedded <script> source (which legitimately carries both modes\' copy as string literals)', () => {
  assert.match(DEFAULT_HTML, /appStoreLabel: 'Download app'/, 'precondition: the class field literal is in the source');
  assert.doesNotMatch(DEFAULT_VISIBLE, /Download app/);
});

// ---------------------------------------------------------------- default state

test('default (APP_STORE_URL empty): renderVals() computes exactly today\'s waitlist copy and live handlers', () => {
  assert.equal(DEFAULT_VALS.appStoreMode, false);
  assert.equal(DEFAULT_VALS.appStoreUrl, '');
  assert.equal(DEFAULT_VALS.heroBtn, 'JOIN THE WAITLIST');
  assert.equal(DEFAULT_VALS.finalBtn, 'JOIN THE WAITLIST');
  assert.equal(DEFAULT_VALS.plateRole, 'button');
  assert.equal(DEFAULT_VALS.plateTabIndex, '0');
  for (let i = 0; i < 5; i++) {
    assert.equal(typeof DEFAULT_VALS['pick' + i], 'function', `pick${i} should be a live handler`);
    assert.equal(typeof DEFAULT_VALS['pickkey' + i], 'function', `pickkey${i} should be a live handler`);
  }
  assert.equal(DEFAULT_VALS.pickAria0, 'Join the waitlist: interested in Apply to jobs');
  assert.equal(DEFAULT_VALS.pickAria1, 'Join the waitlist: interested in Post content');
  assert.equal(DEFAULT_VALS.pickAria2, 'Join the waitlist: interested in Read books');
  assert.equal(DEFAULT_VALS.pickAria3, 'Join the waitlist: interested in Stay fit');
  assert.equal(DEFAULT_VALS.pickAria4, 'Join the waitlist: interested in Live stream');
});

test('default: the nav waitlist link is present, targeting #waitlist', () => {
  assert.match(DEFAULT_VISIBLE, /<a href="#waitlist"[^>]*>JOIN THE WAITLIST<\/a>/);
  assert.doesNotMatch(DEFAULT_VISIBLE, /Download app/);
});

test('default: the Apple mark SVG renders nowhere on the page', () => {
  assert.doesNotMatch(DEFAULT_VISIBLE, APPLE_MARK_RE);
  assert.doesNotMatch(DEFAULT_HTML, APPLE_MARK_RE);
});

test('default: the hero button is present as a real submit button inside a form, not a link', () => {
  assert.match(DEFAULT_HTML, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('default: the closing CTA is present as a real submit button inside a form, not a link', () => {
  const ctaSection = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="cta"'));
  assert.match(ctaSection, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('default: all five interest plates are interactive: click/keyboard handlers, button role, and the waitlist aria-label', () => {
  const plates = [...DEFAULT_HTML.matchAll(/<div data-plate="" onClick="([^"]*)" onKeyDown="([^"]*)" role="([^"]*)" tabIndex="([^"]*)" aria-label="([^"]*)"/g)];
  assert.equal(plates.length, 5, 'expected 5 interest plates');
  const names = ['Apply to jobs', 'Post content', 'Read books', 'Stay fit', 'Live stream'];
  plates.forEach(([, onClick, onKeyDown, role, tabIndex, ariaLabel], i) => {
    assert.equal(onClick, 'fn', `plate ${i} onClick`);
    assert.equal(onKeyDown, 'fn', `plate ${i} onKeyDown`);
    assert.equal(role, 'button', `plate ${i} role`);
    assert.equal(tabIndex, '0', `plate ${i} tabIndex`);
    assert.equal(ariaLabel, `Join the waitlist: interested in ${names[i]}`, `plate ${i} aria-label`);
  });
});

test('default: the #waitlist form (Mailchimp endpoint + honeypot) is present exactly once, in the hero', () => {
  assert.equal((DEFAULT_HTML.match(/id="waitlist"/g) || []).length, 1);
  const w = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="waitlist"'));
  assert.match(w.slice(0, w.indexOf('</section>')), /<input type="email"/);
  assert.doesNotMatch(DEFAULT_HTML, /Not on iPhone\? Get notified for Android/);
});

test('default: focusWaitlist and the #waitlist hash handling are present, unconditionally', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

// ------------------------------------------------------------------- live state

test('live (APP_STORE_URL set): renderVals() reports app-store mode with every plate handler off', () => {
  assert.equal(LIVE_VALS.appStoreMode, true);
  assert.equal(LIVE_VALS.appStoreUrl, APP_STORE_URL);
  assert.equal(LIVE_VALS.appStoreLabel, 'Download app');
  assert.equal(LIVE_VALS.notifyBtn, 'NOTIFY ME');
  assert.equal(LIVE_VALS.plateRole, undefined);
  assert.equal(LIVE_VALS.plateTabIndex, undefined);
  for (let i = 0; i < 5; i++) {
    assert.equal(LIVE_VALS['pick' + i], undefined, `pick${i} should have no handler`);
    assert.equal(LIVE_VALS['pickkey' + i], undefined, `pickkey${i} should have no handler`);
    assert.equal(LIVE_VALS['pickAria' + i], undefined, `pickAria${i} should be absent`);
  }
});

test('live: the nav link points at the App Store URL and reads "Download app"', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  assert.match(desktopNav, new RegExp(`<a href="${escapeRe(APP_STORE_URL)}"[^>]*>`));
  assert.match(desktopNav, /Download app/);
  assert.doesNotMatch(desktopNav, /JOIN THE WAITLIST/);
  // The mobile hamburger drawer is static markup shared with every other page
  // (build/assemble.py's drawer()), generated once at Python build time from
  // this very same APP_STORE_URL constant rather than by this page's
  // client-side template -- so simulating APP_STORE_URL here, on the
  // Component instance, cannot change what the drawer already baked in at
  // build time. This repo's committed build was generated with that Python
  // constant still empty, so the drawer's own copy still reads "JOIN THE
  // WAITLIST" even in this simulated live render; see the drawer()-source
  // tests near the end of this file for coverage of its own live branch.
  assert.equal((LIVE_VISIBLE.match(/JOIN THE WAITLIST/g) || []).length, 1, 'expected only the static mobile drawer link to still say this');
});

test('live: the hero renders a plain App Store link, not a form', () => {
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  assert.match(heroToPhone, new RegExp(`<a href="${escapeRe(APP_STORE_URL)}"[^>]*>`));
  assert.match(heroToPhone, /Download app/);
  assert.doesNotMatch(heroToPhone, /<form/);
  assert.doesNotMatch(heroToPhone, /NO SPAM/, 'the email-specific "no spam" note should not survive next to a download link');
});

test('live: the closing CTA renders a plain App Store link, not a form', () => {
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf('WHAT HAPPENS NEXT'));
  assert.match(ctaSection, new RegExp(`<a href="${escapeRe(APP_STORE_URL)}"[^>]*>`));
  assert.match(ctaSection, /Download app/);
  assert.doesNotMatch(ctaSection, /<form/);
});

test('live: id="fin-form" still exists (the scroll-reveal animation keys off it in both modes)', () => {
  assert.match(LIVE_HTML, /<div id="fin-form"/);
});

test('live: the three App Store links share the same URL and label, and nothing else does', () => {
  const hrefs = [...LIVE_VISIBLE.matchAll(new RegExp(`<a href="(${escapeRe(APP_STORE_URL)})"`, 'g'))];
  assert.equal(hrefs.length, 3, 'expected exactly 3 <a> links to the App Store URL (nav, hero, closing CTA)');
  assert.equal((LIVE_VISIBLE.match(/Download app/g) || []).length, 3);
});

test('live: the Apple mark SVG renders inside the nav link, the hero button and the closing CTA, each before its label', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf('WHAT HAPPENS NEXT'));

  for (const [name, region] of [['nav link', desktopNav], ['hero button', heroToPhone], ['closing CTA', ctaSection]]) {
    assert.match(region, APPLE_MARK_RE, `${name}: Apple mark SVG missing`);
    const markIdx = region.search(APPLE_MARK_RE);
    const labelIdx = region.indexOf('Download app');
    assert.notEqual(labelIdx, -1, `${name}: "Download app" label missing`);
    assert.ok(markIdx < labelIdx, `${name}: the Apple mark should render to the left of the label`);
  }

  // Exactly one mark per button, three total, and nowhere else on the page
  // (the drawer's own copy is generated separately at Python build time; see
  // the dedicated build/assemble.py source tests below, since this build was
  // generated with APP_STORE_URL empty and so does not carry it here).
  assert.equal((LIVE_VISIBLE.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 3);
});

// 2026-09-25 founder feedback: the original 0.8em mark read as "super tiny"
// (~10px on the hero's 12px font). Fixed sizes and a wider gap replace it;
// this pins the exact numbers down so a future edit cannot silently shrink
// them back.
test('live: the Apple mark is 15px in the nav link and 18px in the hero button and closing CTA, each with a 10px gap', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf('WHAT HAPPENS NEXT'));

  assert.match(desktopNav, /<svg aria-hidden="true" viewBox="0 0 384 512" width="15px" height="15px"/, 'nav mark should be 15px square');
  assert.match(heroToPhone, /<svg aria-hidden="true" viewBox="0 0 384 512" width="18px" height="18px"/, 'hero mark should be 18px square');
  assert.match(ctaSection, /<svg aria-hidden="true" viewBox="0 0 384 512" width="18px" height="18px"/, 'closing CTA mark should be 18px square');

  for (const [name, region] of [['nav', desktopNav], ['hero', heroToPhone], ['closing CTA', ctaSection]]) {
    assert.match(region, /gap:10px/, `${name}: expected a 10px icon-to-label gap`);
  }
});

test('live: all five interest plates are inert: no click/keyboard handler, no button role, no waitlist aria-label, content unchanged', () => {
  const plates = [...LIVE_HTML.matchAll(/<div data-plate="" onClick="([^"]*)" onKeyDown="([^"]*)" role="([^"]*)" tabIndex="([^"]*)" aria-label="([^"]*)"/g)];
  assert.equal(plates.length, 5, 'expected 5 interest plate wrapper divs to still exist');
  plates.forEach(([, onClick, onKeyDown, role, tabIndex, ariaLabel], i) => {
    assert.equal(onClick, '', `plate ${i} onClick should be gone`);
    assert.equal(onKeyDown, '', `plate ${i} onKeyDown should be gone`);
    assert.equal(role, '', `plate ${i} role should be gone`);
    assert.equal(tabIndex, '', `plate ${i} tabIndex should be gone`);
    assert.equal(ariaLabel, '', `plate ${i} aria-label should be gone`);
  });
  assert.doesNotMatch(LIVE_VISIBLE, /Join the waitlist: interested in/);
  // The five headings/content are untouched.
  for (const name of ['Apply to jobs', 'Post content', 'Read books', 'Stay fit', 'Live stream']) {
    assert.match(LIVE_HTML, new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
  assert.match(LIVE_HTML, /I WANT THIS HUNT/, 'plate copy is kept, only interactivity is removed');
});

test('live: the waitlist form survives exactly once, relocated to the bottom and retitled for Android, with the same Mailchimp endpoint', () => {
  assert.equal((LIVE_VISIBLE.match(/id="waitlist"/g) || []).length, 1, 'exactly one #waitlist in the live DOM');
  assert.equal((LIVE_VISIBLE.match(/Not on iPhone\? Get notified for Android/g) || []).length, 1);
  assert.equal((LIVE_VISIBLE.match(/NOTIFY ME/g) || []).length, 1);

  const androidSectionStart = LIVE_VISIBLE.indexOf('Not on iPhone');
  const androidSection = LIVE_VISIBLE.slice(LIVE_VISIBLE.lastIndexOf('<section', androidSectionStart));
  assert.match(androidSection, /id="waitlist"/, 'the relocated section carries the #waitlist id');
  assert.match(androidSection, /<input type="email"/);
  assert.match(androidSection, />NOTIFY ME</);

  // It is physically the last section before the footer.
  const footerIdx = LIVE_VISIBLE.indexOf('<footer');
  assert.ok(androidSectionStart < footerIdx && footerIdx - androidSectionStart < 2000,
    'the Android waitlist section should sit immediately before the footer');

  // Same backend as before: no second Mailchimp integration was introduced.
  // (The generic "list-manage.com/subscribe/post?u=..." pattern also matches
  // the WAITLIST_ENDPOINT doc comment above the field, so this checks the
  // real, fully-qualified audience endpoint specifically: the same string
  // build/check.py's MC_ENDPOINT check uses.)
  assert.equal((html.match(/huntz\.us18\.list-manage\.com\/subscribe\/post/g) || []).length, 1);
  assert.match(html, /WAITLIST_HONEYPOT = 'b_b7144d02c740628b3280ff55f_3ee28a30af'/);
});

test('live: focusWaitlist and the #waitlist hash handling are untouched and still generic (getElementById, no mode branching)', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /var w = document\.getElementById\('waitlist'\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

test('live: the mobile nav-hide rule hides the App Store link too, without reading the JS constant', () => {
  assert.match(html, /a\[href="#waitlist"\],#hz-nav a\[href="https:\/\/apps\.apple\.com\/app\/id6802558635"\]\{display:none !important\}/);
});

// ---------------------------------------------- the shared drawer (technique 3)

// build/assemble.py's drawer() is called for every page (index.html and every
// content page) and bakes its waitlist/App Store link once, at Python build
// time, from the module-level APP_STORE_URL constant -- see this file's own
// header comment above for why that makes it untestable via index.html's
// rendered output. isolate the function's own source text instead, the same
// way techniques 1 and 2 above trust index.html's source as ground truth.
const assemblePy = fs.readFileSync(path.join(ROOT, 'build', 'assemble.py'), 'utf8');
const drawerStart = assemblePy.indexOf('def drawer(');
const drawerEnd = assemblePy.indexOf('def footer_nav(');
assert.ok(drawerStart !== -1 && drawerEnd !== -1 && drawerStart < drawerEnd,
  'build/assemble.py: could not isolate the drawer() function source');
const drawerSrc = assemblePy.slice(drawerStart, drawerEnd);

test('live: build/assemble.py\'s drawer() carries the Apple mark and reads "Download app" once APP_STORE_URL is set', () => {
  assert.match(drawerSrc, /if APP_STORE_URL and app_store:/,
    'drawer() has no APP_STORE_URL conditional (guarded by its own app_store opt-out)');
  const liveBranch = drawerSrc.slice(drawerSrc.indexOf('if APP_STORE_URL and app_store:'), drawerSrc.indexOf('else:'));
  assert.match(liveBranch, /apple_mark\(18\)/, 'drawer() live branch should use the shared 18px Apple mark');
  assert.match(liveBranch, /gap:10px/, 'drawer() live branch should use a 10px icon-to-label gap');
  assert.match(liveBranch, /Download app/, 'drawer() live branch does not read "Download app"');
  assert.match(liveBranch, /href="\{APP_STORE_URL\}"/, 'drawer() live branch does not link to APP_STORE_URL');
  assert.doesNotMatch(liveBranch, /JOIN THE WAITLIST/);
});

// hunt-fallback.html ("limited beta", no App Store claims) and auth/callback
// .html (account-agnostic, no App Store claims) each embed this same shared
// drawer but must never show the App Store link, regardless of the site-wide
// switch -- their own build/check.py rules forbid it outright. A regression
// here would only surface once APP_STORE_URL actually goes live (exactly the
// failure mode this whole file exists to catch ahead of time).
test('drawer() call sites: hunt-fallback.html and auth/callback.html opt out of the App Store link (app_store=False)', () => {
  for (const route of ['/hunt', '/auth/callback']) {
    const call = new RegExp(`drawer\\("${escapeRe(route)}",\\s*"[^"]*",\\s*app_store=False\\)`);
    assert.match(assemblePy, call, `build/assemble.py: drawer("${route}", ...) should pass app_store=False`);
  }
});

test('default: build/assemble.py\'s drawer() default branch stays plain "JOIN THE WAITLIST" with no Apple mark', () => {
  assert.match(drawerSrc, /\belse:/, 'drawer() has no default-branch else clause');
  // Sliced up to the function's own return statement, not to the end of
  // drawerSrc, so this does not spill into unrelated markup below (e.g. the
  // header row's own "gap:14px") that has nothing to do with this branch.
  const defaultBranch = drawerSrc.slice(drawerSrc.indexOf('else:'), drawerSrc.indexOf('return f"""'));
  assert.match(defaultBranch, /href="\{waitlist_href\}"/, 'default branch does not link to waitlist_href');
  assert.match(defaultBranch, />JOIN THE WAITLIST<\/a>/);
  assert.doesNotMatch(defaultBranch, /apple_mark\(/);
  assert.doesNotMatch(defaultBranch, /Download app/);
  // No icon means no icon-to-label gap: the exact same style this branch
  // has always had, with nothing added for this feature.
  assert.doesNotMatch(defaultBranch, /gap:/);
});

// ------------------------------------------ content pages + blog (technique 4)

const SHARED_CHROME_PAGES = [
  'how-it-works.html', 'faq.html', 'about.html', 'contact.html',
  'accountability-challenges.html', 'blog.html',
  'blog/best-accountability-apps-2026.html', 'blog/why-you-dont-achieve-your-goals.html',
];

for (const rel of SHARED_CHROME_PAGES) {
  test(`default: ${rel} still carries the shared waitlist nav pill and closing CTA block`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.match(t, /<a data-hz-desknav href="\/#waitlist" style="font:700 11px[^>]*>JOIN THE WAITLIST<\/a>/,
      'desktop nav pill missing or changed');
    assert.match(t, /Ready when you are<span style="color:#C24E1F">\.<\/span>/, 'closing heading missing or changed');
    assert.match(t, /Join the waitlist and we'll email you when the first Hunts open\./, 'closing paragraph missing or changed');
    assert.match(t, /<a href="\/#waitlist" style="display:inline-block[^>]*>JOIN THE WAITLIST &#8594;<\/a>/,
      'closing button missing or changed');
    assert.doesNotMatch(t, /Huntz is on the App Store/);
    assert.doesNotMatch(t, /Download app/);
    assert.doesNotMatch(t, APPLE_MARK_RE);
  });
}

// Each of these four pages also carries its own in-copy waitlist sentence
// (build/pages/<slug>.json), separate from the shared chrome above.
test('default: about.html\'s in-copy sentence still points at the waitlist', () => {
  const t = fs.readFileSync(path.join(ROOT, 'about.html'), 'utf8');
  assert.match(t, /Self-service tools for creators to launch Hunts independently are planned for later\. The <a href="\/#waitlist"[^>]*>waitlist<\/a> is the way in\./);
});

test('default: faq.html\'s "Is Huntz available right now?" answer still says "Not yet."', () => {
  const t = fs.readFileSync(path.join(ROOT, 'faq.html'), 'utf8');
  assert.match(t, /Not yet\. The first Hunts are being developed now with our first creators\. <a href="\/#waitlist"[^>]*>Join the waitlist<\/a> and we will email you when they open\./);
});

test('default: how-it-works.html\'s in-copy sentence still points at the waitlist', () => {
  const t = fs.readFileSync(path.join(ROOT, 'how-it-works.html'), 'utf8');
  assert.match(t, /The first Hunts are being developed now, directly with our first creators\. <a href="\/#waitlist"[^>]*>Join the waitlist<\/a> and we will email you when they open\./);
});

test('default: contact.html\'s troubleshooting bullet still says "the waitlist"', () => {
  const t = fs.readFileSync(path.join(ROOT, 'contact.html'), 'utf8');
  assert.match(t, /Problems with the waitlist or this website: tell us what broke and on what device\./);
});

// The explicit byte-for-byte guarantee (README/build/assemble.py's own
// promise, section 1 of this feature): pinned as a hash rather than a huge
// inline literal, so any change at all to the default-state page, however
// small, fails this test rather than only the broader checks above.
test('default: about.html is byte-for-byte the committed page (sha256 pin)', () => {
  const bytes = fs.readFileSync(path.join(ROOT, 'about.html'));
  const hash = crypto.createHash('sha256').update(bytes).digest('hex');
  assert.equal(hash, '51749417cfb8b0985b8e058d8fe12c5fc983905dbcd4f20991b0612cf15f6109',
    'about.html changed: the default (empty APP_STORE_URL) state must stay byte-for-byte identical to the committed page');
});

// ---- live state: build/assemble.py source (content pages cannot show a
// second state from one committed build; see the header comment above) ----

// Sliced up to the next comment/assignment, not all the way to the next
// constant, so neither slice picks up build/assemble.py's own prose (which
// legitimately says "waitlist" while explaining the switch).
const navPillLiveSrc = assemblePy.slice(assemblePy.indexOf('NAV_PILL_LIVE = ('),
  assemblePy.indexOf("# The heading's own margin-bottom"));
const closingBlockLiveSrc = assemblePy.slice(assemblePy.indexOf('CLOSING_BLOCK_LIVE = ('), assemblePy.indexOf('def apply_content_app_store_switch'));

test('live: build/assemble.py\'s NAV_PILL_LIVE carries the 15px Apple mark, "Download app", a pill radius and the App Store href', () => {
  assert.match(navPillLiveSrc, /apple_mark\(15\)/);
  assert.match(navPillLiveSrc, /Download app/);
  assert.match(navPillLiveSrc, /href="\{APP_STORE_URL\}"/);
  assert.match(navPillLiveSrc, /border-radius:999px/);
  assert.doesNotMatch(navPillLiveSrc, /JOIN THE WAITLIST/);
});

test('live: build/assemble.py\'s CLOSING_BLOCK_LIVE reads "Huntz is on the App Store.", carries the 18px mark, and no longer buttons to /#waitlist', () => {
  assert.match(closingBlockLiveSrc, /Huntz is on the App Store/);
  assert.match(closingBlockLiveSrc, /apple_mark\(18\)/);
  assert.match(closingBlockLiveSrc, /Download app/);
  assert.match(closingBlockLiveSrc, /href="\{APP_STORE_URL\}"/);
  // The main CTA button no longer points at /#waitlist; only the small
  // Android fallback link below it does. Sliced up to that link's own
  // wrapper div, i.e. before its href, not up to its inner text.
  const ctaOnly = closingBlockLiveSrc.slice(0, closingBlockLiveSrc.indexOf('margin-top:14px'));
  assert.doesNotMatch(ctaOnly, /href="\/#waitlist"/, 'the main CTA button should not still point at #waitlist');
  // Two separate checks, not one spanning regex: build/assemble.py wraps
  // this string across several Python literals, so the raw source has a
  // quote/newline seam between the style attribute and the link text.
  assert.match(closingBlockLiveSrc, /href="\/#waitlist" style="font:600 11px/);
  assert.match(closingBlockLiveSrc, /Not on iPhone\? Get notified for Android\.<\/a><\/div>/);
});

test('live: no leftover "waitlist" wording in NAV_PILL_LIVE or CLOSING_BLOCK_LIVE, except the Android link\'s href', () => {
  for (const [name, src] of [['NAV_PILL_LIVE', navPillLiveSrc], ['CLOSING_BLOCK_LIVE', closingBlockLiveSrc]]) {
    const withoutAndroidHref = src.split('href="/#waitlist"').join('');
    assert.doesNotMatch(withoutAndroidHref, /waitlist/i, `${name}: unexpected leftover "waitlist" wording`);
  }
});

test('live: apply_content_app_store_switch() is wired to all three page shells (content, article, blog hub)', () => {
  for (const tplFile of ['content-page.html', 'article-page.html', 'blog-index.html']) {
    const pattern = new RegExp(`apply_content_app_store_switch\\(\\(BUILD / "${escapeRe(tplFile)}"\\)\\.read_text\\(\\)\\)`);
    assert.match(assemblePy, pattern, `build/assemble.py: ${tplFile} is not wrapped in apply_content_app_store_switch()`);
  }
});

test('live: about.json gets a launch-state in-copy sentence and meta description', () => {
  assert.match(assemblePy, />app<\/a> is the way in\.<\/p>/, 'about: expected "...the app is the way in." sentence not found');
  assert.match(assemblePy, /Built in Oakland by Huntz, Inc\. Available now on the App Store\./);
});

test('live: accountability-challenges.json gets a launch-state meta description', () => {
  assert.match(assemblePy, /stakes and published rules\. Available now on the App Store\./);
});

test('live: contact.json gets a launch-state meta description and troubleshooting bullet', () => {
  assert.match(assemblePy, /Questions about accountability challenges, the app, privacy, or partnerships:/);
  assert.match(assemblePy, /Problems with the app or this website:/);
});

test('live: faq.json\'s "Is Huntz available right now?" answer becomes "Yes." with a download link, and the meta description drops "waitlist"', () => {
  assert.match(assemblePy, /Huntz is live: the iOS app is available/);
  assert.match(assemblePy, /Yes\. Huntz is live on the App Store, with the first Hunts developed directly with/);
  assert.match(assemblePy, />Download the app<\/a> to join one\./);
});

test('live: how-it-works.json\'s in-copy sentence becomes "The first Hunts are live in the app."', () => {
  assert.match(assemblePy, /The first Hunts are live in /);
  assert.match(assemblePy, />the app<\/a>\.<\/p>/);
});

// -------------------------------------------------------------- meta tag

const APPLE_ITUNES_META = '<meta name="apple-itunes-app" content="app-id=6802558635">';

const PUBLIC_PAGES = [
  'index.html', 'how-it-works.html', 'faq.html', 'about.html', 'contact.html',
  'accountability-challenges.html', 'blog.html',
  'blog/best-accountability-apps-2026.html', 'blog/why-you-dont-achieve-your-goals.html',
  'terms.html', 'privacy.html',
];

for (const rel of PUBLIC_PAGES) {
  test(`Smart App Banner meta tag is present in the <head> of ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.ok(t.indexOf(APPLE_ITUNES_META) > 0, `${rel}: missing ${APPLE_ITUNES_META}`);
    assert.ok(t.indexOf(APPLE_ITUNES_META) < t.indexOf('</head>'), `${rel}: meta tag is outside <head>`);
  });
}

const UTILITY_PAGES = [
  'auth/callback.html',
  'mailbox/gmail-action/pair.html',
  'payouts/return.html',
  'payouts/refresh.html',
];

for (const rel of UTILITY_PAGES) {
  test(`Smart App Banner meta tag is absent from the noindex utility page ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.doesNotMatch(t, /apple-itunes-app/, `${rel}: should not carry the Smart App Banner`);
    // These are exactly the "noindex utility" pages this feature must skip.
    assert.match(t, /name="robots" content="noindex/, `${rel}: expected to be a noindex page`);
  });
}
