'use strict';
// Tests for the App Store launch switch (2026-09-25 founder decision):
// index.html's Component class gains an APP_STORE_URL config field, next to
// WAITLIST_ENDPOINT, that flips the home page from "join the waitlist" to
// "download on the App Store" once set. See README.md, "App Store launch
// switch".
//
//     npm test          (or: node --test "test/*.test.js")
//
// index.html is generated by build/assemble.py (see build/check.py's own
// "unfilled build placeholder" rule) and is not hand-edited, so these tests
// read the committed file the same way build/check.py does.
//
// Two complementary techniques evaluate the page in both states without a
// browser:
//
//   1. The Component class is a plain, DOM-free-at-render JS class (its
//      renderVals() touches no DOM), so it is extracted from its
//      <script type="text/x-dc" data-dc-script> block and evaluated the same
//      way the page's own runtime does (assets/app.*.js's evalDcLogic:
//      new Function('DCLogic','StreamableLogic','React', src + ...)),
//      mirroring how gmail-pair.test.js and payout-return.test.js vm-execute
//      this page's plain <script> blocks. This gives the exact computed
//      values (button text, which of pick0..pick4 are live handlers, the
//      link href/label) for a given APP_STORE_URL.
//   2. A small, deliberately minimal re-implementation of this template
//      system's two primitives: {{ expr }} interpolation and
//      <sc-if value="{{ expr }}">...</sc-if> conditional blocks. It resolves
//      the static markup against those same computed values, so assertions
//      read like "what's on the page" rather than "what's in the template
//      source". It does not need sc-for (unused by the pieces under test).

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const APP_STORE_URL = 'https://apps.apple.com/app/id6802558635';

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// ------------------------------------------------------------- the harness

const scriptMatch = html.match(/<script type="text\/x-dc" data-dc-script[^>]*>([\s\S]*?)<\/script>/);
assert.ok(scriptMatch, 'index.html: could not find the <script type="text/x-dc" data-dc-script> block');
const componentSrc = scriptMatch[1];

class FakeLogic {
  constructor(props) { this.props = props || {}; this.state = {}; }
  setState(update) {
    const patch = typeof update === 'function' ? update(this.state) : update;
    Object.assign(this.state, patch);
  }
  forceUpdate() {}
  componentDidMount() {}
  componentDidUpdate() {}
  componentWillUnmount() {}
  renderVals() { return {}; }
}

// Mirrors assets/app.*.js's evalDcLogic() exactly (same three globals, same
// trailing expression), so this is the real evaluation path, not a guess at it.
const ComponentClass = new Function('DCLogic', 'StreamableLogic', 'React',
  componentSrc + '\n;return (typeof Component!=="undefined"&&Component)||undefined;'
)(FakeLogic, FakeLogic, {});
assert.equal(typeof ComponentClass, 'function', 'index.html: class Component extends DCLogic not found/evaluable');

/** renderVals() for a fresh instance with the given APP_STORE_URL ('' = default/off). */
function valsFor(appStoreUrl) {
  const c = new ComponentClass();
  c.APP_STORE_URL = appStoreUrl;
  return c.renderVals();
}

const DEFAULT_VALS = valsFor('');
const LIVE_VALS = valsFor(APP_STORE_URL);

// ---------------------------------------------------------- template micro-resolver

function resolveExpr(vals, expr) {
  expr = expr.trim();
  if (expr[0] === '!') return !resolveExpr(vals, expr.slice(1));
  if (expr === 'true') return true;
  if (expr === 'false') return false;
  return vals[expr];
}

/** Index of the </sc-if> that matches the <sc-if ...> whose '>' is at openEnd. */
function findMatchingClose(src, openEnd) {
  let depth = 1;
  let i = openEnd;
  for (;;) {
    const nextOpen = src.indexOf('<sc-if', i);
    const nextClose = src.indexOf('</sc-if>', i);
    if (nextClose === -1) throw new Error('unmatched <sc-if> in index.html');
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth++;
      i = src.indexOf('>', nextOpen) + 1;
    } else {
      depth--;
      if (depth === 0) return nextClose;
      i = nextClose + '</sc-if>'.length;
    }
  }
}

/**
 * Resolves {{ expr }} interpolation and nested <sc-if value="{{ expr }}">
 * blocks against `vals`, the same object the real runtime's renderVals()
 * produces. A function-valued expression (an event handler) renders as the
 * literal "fn" marker, present vs. absent being exactly what matters for the
 * plates' onClick/onKeyDown. Good enough for this page's own template
 * (sc-for is not used by anything under test, so it is left unhandled).
 */
function renderTemplate(src, vals) {
  let out = '';
  let i = 0;
  for (;;) {
    const nextTag = src.indexOf('<sc-if', i);
    if (nextTag === -1) { out += src.slice(i); break; }
    out += src.slice(i, nextTag);
    const tagEnd = src.indexOf('>', nextTag) + 1;
    const tagText = src.slice(nextTag, tagEnd);
    const exprMatch = tagText.match(/value="\{\{([^}]+)\}\}"/);
    const closeIdx = findMatchingClose(src, tagEnd);
    const inner = src.slice(tagEnd, closeIdx);
    const keep = exprMatch ? resolveExpr(vals, exprMatch[1]) : false;
    out += keep ? renderTemplate(inner, vals) : '';
    i = closeIdx + '</sc-if>'.length;
  }
  return out.replace(/\{\{\s*([^}]+?)\s*\}\}/g, (_, expr) => {
    const v = resolveExpr(vals, expr);
    if (v === undefined || v === null || v === false) return '';
    if (typeof v === 'function') return 'fn';
    return String(v);
  });
}

// Sanity-check the micro-resolver itself against a case with a known answer,
// before trusting it for the real assertions below.
test('sanity: the template micro-resolver keeps only the true sc-if branch and drops the other', () => {
  const t = '<sc-if value="{{ a }}">YES</sc-if><sc-if value="{{ !a }}">NO</sc-if><p>{{ b }}</p>';
  assert.equal(renderTemplate(t, { a: true, b: 'hi' }), 'YES<p>hi</p>');
  assert.equal(renderTemplate(t, { a: false, b: 'hi' }), 'NO<p>hi</p>');
});

const DEFAULT_HTML = renderTemplate(html, DEFAULT_VALS);
const LIVE_HTML = renderTemplate(html, LIVE_VALS);

/**
 * The Component class's own JS source (inside <script type="text/x-dc"
 * data-dc-script>) necessarily contains both 'JOIN THE WAITLIST' and
 * 'DOWNLOAD ON THE APP STORE' as string literals: renderVals() has to
 * compute both regardless of which one is live, since which mode is active
 * isn't known until a real instance's APP_STORE_URL is read. Likewise the
 * mobile nav-hide rule in <style> spells out the App Store URL so it can
 * match it without reading the JS constant (its own dedicated test below).
 * Neither is rendered markup, so whole-page "does this text appear on the
 * page" checks scope to everything outside <script>/<style> tags.
 */
function visibleMarkup(rendered) {
  return rendered.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<style[^>]*>[\s\S]*?<\/style>/g, '');
}

const DEFAULT_VISIBLE = visibleMarkup(DEFAULT_HTML);
const LIVE_VISIBLE = visibleMarkup(LIVE_HTML);

test('sanity: visibleMarkup strips embedded <script> source (which legitimately carries both modes\' copy as string literals)', () => {
  assert.match(DEFAULT_HTML, /appStoreLabel: 'DOWNLOAD ON THE APP STORE'/, 'precondition: the class field literal is in the source');
  assert.doesNotMatch(DEFAULT_VISIBLE, /DOWNLOAD ON THE APP STORE/);
});

// ---------------------------------------------------------------- default state

test('default (APP_STORE_URL empty): renderVals() computes exactly today\'s waitlist copy and live handlers', () => {
  assert.equal(DEFAULT_VALS.appStoreMode, false);
  assert.equal(DEFAULT_VALS.appStoreUrl, '');
  assert.equal(DEFAULT_VALS.heroBtn, 'JOIN THE WAITLIST');
  assert.equal(DEFAULT_VALS.finalBtn, 'JOIN THE WAITLIST');
  assert.equal(DEFAULT_VALS.plateRole, 'button');
  assert.equal(DEFAULT_VALS.plateTabIndex, '0');
  for (let i = 0; i < 5; i++) {
    assert.equal(typeof DEFAULT_VALS['pick' + i], 'function', `pick${i} should be a live handler`);
    assert.equal(typeof DEFAULT_VALS['pickkey' + i], 'function', `pickkey${i} should be a live handler`);
  }
  assert.equal(DEFAULT_VALS.pickAria0, 'Join the waitlist: interested in Apply to jobs');
  assert.equal(DEFAULT_VALS.pickAria1, 'Join the waitlist: interested in Post content');
  assert.equal(DEFAULT_VALS.pickAria2, 'Join the waitlist: interested in Read books');
  assert.equal(DEFAULT_VALS.pickAria3, 'Join the waitlist: interested in Stay fit');
  assert.equal(DEFAULT_VALS.pickAria4, 'Join the waitlist: interested in Live stream');
});

test('default: the nav waitlist link is present, targeting #waitlist', () => {
  assert.match(DEFAULT_VISIBLE, /<a href="#waitlist"[^>]*>JOIN THE WAITLIST<\/a>/);
  assert.doesNotMatch(DEFAULT_VISIBLE, /DOWNLOAD ON THE APP STORE/);
});

test('default: the hero button is present as a real submit button inside a form, not a link', () => {
  assert.match(DEFAULT_HTML, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('default: the closing CTA is present as a real submit button inside a form, not a link', () => {
  const ctaSection = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="cta"'));
  assert.match(ctaSection, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('default: all five interest plates are interactive: click/keyboard handlers, button role, and the waitlist aria-label', () => {
  const plates = [...DEFAULT_HTML.matchAll(/<div data-plate="" onClick="([^"]*)" onKeyDown="([^"]*)" role="([^"]*)" tabIndex="([^"]*)" aria-label="([^"]*)"/g)];
  assert.equal(plates.length, 5, 'expected 5 interest plates');
  const names = ['Apply to jobs', 'Post content', 'Read books', 'Stay fit', 'Live stream'];
  plates.forEach(([, onClick, onKeyDown, role, tabIndex, ariaLabel], i) => {
    assert.equal(onClick, 'fn', `plate ${i} onClick`);
    assert.equal(onKeyDown, 'fn', `plate ${i} onKeyDown`);
    assert.equal(role, 'button', `plate ${i} role`);
    assert.equal(tabIndex, '0', `plate ${i} tabIndex`);
    assert.equal(ariaLabel, `Join the waitlist: interested in ${names[i]}`, `plate ${i} aria-label`);
  });
});

test('default: the #waitlist form (Mailchimp endpoint + honeypot) is present exactly once, in the hero', () => {
  assert.equal((DEFAULT_HTML.match(/id="waitlist"/g) || []).length, 1);
  const w = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="waitlist"'));
  assert.match(w.slice(0, w.indexOf('</section>')), /<input type="email"/);
  assert.doesNotMatch(DEFAULT_HTML, /Not on iPhone\? Get notified for Android/);
});

test('default: focusWaitlist and the #waitlist hash handling are present, unconditionally', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

// ------------------------------------------------------------------- live state

test('live (APP_STORE_URL set): renderVals() reports app-store mode with every plate handler off', () => {
  assert.equal(LIVE_VALS.appStoreMode, true);
  assert.equal(LIVE_VALS.appStoreUrl, APP_STORE_URL);
  assert.equal(LIVE_VALS.appStoreLabel, 'DOWNLOAD ON THE APP STORE');
  assert.equal(LIVE_VALS.notifyBtn, 'NOTIFY ME');
  assert.equal(LIVE_VALS.plateRole, undefined);
  assert.equal(LIVE_VALS.plateTabIndex, undefined);
  for (let i = 0; i < 5; i++) {
    assert.equal(LIVE_VALS['pick' + i], undefined, `pick${i} should have no handler`);
    assert.equal(LIVE_VALS['pickkey' + i], undefined, `pickkey${i} should have no handler`);
    assert.equal(LIVE_VALS['pickAria' + i], undefined, `pickAria${i} should be absent`);
  }
});

test('live: the nav link points at the App Store URL and reads "DOWNLOAD ON THE APP STORE"', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  assert.match(desktopNav, new RegExp(`<a href="${APP_STORE_URL.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')}"[^>]*>DOWNLOAD ON THE APP STORE</a>`));
  assert.doesNotMatch(desktopNav, /JOIN THE WAITLIST/);
  // The mobile hamburger drawer is static markup shared with every other page
  // (build/assemble.py's drawer()), outside this page's reactive template, so
  // it cannot read APP_STORE_URL and is intentionally left saying "JOIN THE
  // WAITLIST": this is the one known, disclosed gap in the launch switch.
  assert.equal((LIVE_VISIBLE.match(/JOIN THE WAITLIST/g) || []).length, 1, 'expected only the static mobile drawer link to still say this');
});

test('live: the hero renders a plain App Store link, not a form', () => {
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  assert.match(heroToPhone, new RegExp(`<a href="${APP_STORE_URL.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')}"[^>]*>DOWNLOAD ON THE APP STORE</a>`));
  assert.doesNotMatch(heroToPhone, /<form/);
  assert.doesNotMatch(heroToPhone, /NO SPAM/, 'the email-specific "no spam" note should not survive next to a download link');
});

test('live: the closing CTA renders a plain App Store link, not a form', () => {
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf('WHAT HAPPENS NEXT'));
  assert.match(ctaSection, new RegExp(`<a href="${APP_STORE_URL.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')}"[^>]*>DOWNLOAD ON THE APP STORE</a>`));
  assert.doesNotMatch(ctaSection, /<form/);
});

test('live: id="fin-form" still exists (the scroll-reveal animation keys off it in both modes)', () => {
  assert.match(LIVE_HTML, /<div id="fin-form"/);
});

test('live: the three App Store links share the same URL and label, and nothing else does', () => {
  const hrefs = [...LIVE_VISIBLE.matchAll(new RegExp(`<a href="(${APP_STORE_URL.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})"`, 'g'))];
  assert.equal(hrefs.length, 3, 'expected exactly 3 <a> links to the App Store URL (nav, hero, closing CTA)');
  assert.equal((LIVE_VISIBLE.match(/DOWNLOAD ON THE APP STORE/g) || []).length, 3);
});

test('live: all five interest plates are inert: no click/keyboard handler, no button role, no waitlist aria-label, content unchanged', () => {
  const plates = [...LIVE_HTML.matchAll(/<div data-plate="" onClick="([^"]*)" onKeyDown="([^"]*)" role="([^"]*)" tabIndex="([^"]*)" aria-label="([^"]*)"/g)];
  assert.equal(plates.length, 5, 'expected 5 interest plate wrapper divs to still exist');
  plates.forEach(([, onClick, onKeyDown, role, tabIndex, ariaLabel], i) => {
    assert.equal(onClick, '', `plate ${i} onClick should be gone`);
    assert.equal(onKeyDown, '', `plate ${i} onKeyDown should be gone`);
    assert.equal(role, '', `plate ${i} role should be gone`);
    assert.equal(tabIndex, '', `plate ${i} tabIndex should be gone`);
    assert.equal(ariaLabel, '', `plate ${i} aria-label should be gone`);
  });
  assert.doesNotMatch(LIVE_VISIBLE, /Join the waitlist: interested in/);
  // The five headings/content are untouched.
  for (const name of ['Apply to jobs', 'Post content', 'Read books', 'Stay fit', 'Live stream']) {
    assert.match(LIVE_HTML, new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
  assert.match(LIVE_HTML, /I WANT THIS HUNT/, 'plate copy is kept, only interactivity is removed');
});

test('live: the waitlist form survives exactly once, relocated to the bottom and retitled for Android, with the same Mailchimp endpoint', () => {
  assert.equal((LIVE_VISIBLE.match(/id="waitlist"/g) || []).length, 1, 'exactly one #waitlist in the live DOM');
  assert.equal((LIVE_VISIBLE.match(/Not on iPhone\? Get notified for Android/g) || []).length, 1);
  assert.equal((LIVE_VISIBLE.match(/NOTIFY ME/g) || []).length, 1);

  const androidSectionStart = LIVE_VISIBLE.indexOf('Not on iPhone');
  const androidSection = LIVE_VISIBLE.slice(LIVE_VISIBLE.lastIndexOf('<section', androidSectionStart));
  assert.match(androidSection, /id="waitlist"/, 'the relocated section carries the #waitlist id');
  assert.match(androidSection, /<input type="email"/);
  assert.match(androidSection, />NOTIFY ME</);

  // It is physically the last section before the footer.
  const footerIdx = LIVE_VISIBLE.indexOf('<footer');
  assert.ok(androidSectionStart < footerIdx && footerIdx - androidSectionStart < 2000,
    'the Android waitlist section should sit immediately before the footer');

  // Same backend as before: no second Mailchimp integration was introduced.
  // (The generic "list-manage.com/subscribe/post?u=..." pattern also matches
  // the WAITLIST_ENDPOINT doc comment above the field, so this checks the
  // real, fully-qualified audience endpoint specifically: the same string
  // build/check.py's MC_ENDPOINT check uses.)
  assert.equal((html.match(/huntz\.us18\.list-manage\.com\/subscribe\/post/g) || []).length, 1);
  assert.match(html, /WAITLIST_HONEYPOT = 'b_b7144d02c740628b3280ff55f_3ee28a30af'/);
});

test('live: focusWaitlist and the #waitlist hash handling are untouched and still generic (getElementById, no mode branching)', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /var w = document\.getElementById\('waitlist'\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

test('live: the mobile nav-hide rule hides the App Store link too, without reading the JS constant', () => {
  assert.match(html, /a\[href="#waitlist"\],#hz-nav a\[href="https:\/\/apps\.apple\.com\/app\/id6802558635"\]\{display:none !important\}/);
});

// -------------------------------------------------------------- meta tag

const APPLE_ITUNES_META = '<meta name="apple-itunes-app" content="app-id=6802558635">';

const PUBLIC_PAGES = [
  'index.html', 'how-it-works.html', 'faq.html', 'about.html', 'contact.html',
  'accountability-challenges.html', 'blog.html',
  'blog/best-accountability-apps-2026.html', 'blog/why-you-dont-achieve-your-goals.html',
  'terms.html', 'privacy.html',
];

for (const rel of PUBLIC_PAGES) {
  test(`Smart App Banner meta tag is present in the <head> of ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.ok(t.indexOf(APPLE_ITUNES_META) > 0, `${rel}: missing ${APPLE_ITUNES_META}`);
    assert.ok(t.indexOf(APPLE_ITUNES_META) < t.indexOf('</head>'), `${rel}: meta tag is outside <head>`);
  });
}

const UTILITY_PAGES = [
  'auth/callback.html',
  'mailbox/gmail-action/pair.html',
  'payouts/return.html',
  'payouts/refresh.html',
];

for (const rel of UTILITY_PAGES) {
  test(`Smart App Banner meta tag is absent from the noindex utility page ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.doesNotMatch(t, /apple-itunes-app/, `${rel}: should not carry the Smart App Banner`);
    // These are exactly the "noindex utility" pages this feature must skip.
    assert.match(t, /name="robots" content="noindex/, `${rel}: expected to be a noindex page`);
  });
}
