'use strict';
// Tests for the App Store launch switch (2026-09-25 founder decision; on
// since launch day, 2026-10-09): index.html's Component class gains an
// APP_STORE_URL config field, next to WAITLIST_ENDPOINT, that flips the home
// page from "join the waitlist" to "download on the App Store" once set: the
// nav link becomes a pill-shaped "Download app" link carrying an inline Apple
// mark, and the hero and the closing CTA carry Apple's own "Download on the
// App Store" badge (founder revision, 2026-10-09; its artwork, size and
// clear-space rules are asserted in test/app-store-badge.test.js). The same
// build-time APP_STORE_URL
// constant also drives the shared mobile drawer (build/assemble.py's
// drawer()), the inner pages' nav pill and closing block, four pages'
// in-copy sentences and the home page's "What's live" card (the "What
// happens next" card until the launch copy mix, 2026-10-09, which also
// turned the Upcoming plates into links to the live Hunts; see
// test/launch-copy.test.js). See README.md, "App Store launch switch".
//
//     npm test          (or: node --test "test/*.test.js")
//
// index.html is generated by build/assemble.py (see build/check.py's own
// "unfilled build placeholder" rule) and is not hand-edited, so these tests
// read the committed file the same way build/check.py does.
//
// The committed build is the launched site: build/assemble.py's
// APP_STORE_URL is set. Three complementary techniques evaluate the feature
// in both states without a browser; which state each one can observe depends
// on where the markup is produced:
//
//   1. The Component class is a plain, DOM-free-at-render JS class (its
//      renderVals() touches no DOM), so it is extracted from its
//      <script type="text/x-dc" data-dc-script> block and evaluated the same
//      way the page's own runtime does (assets/app.*.js's evalDcLogic:
//      new Function('DCLogic','StreamableLogic','React', src + ...)),
//      mirroring how gmail-pair.test.js and payout-return.test.js vm-execute
//      this page's plain <script> blocks. This gives the exact computed
//      values (button text, which of pick0..pick4 are live handlers, the
//      link href/label) for a given APP_STORE_URL.
//   2. A small, deliberately minimal re-implementation of this template
//      system's two primitives: {{ expr }} interpolation and
//      <sc-if value="{{ expr }}">...</sc-if> conditional blocks. It resolves
//      the static markup against those same computed values, so assertions
//      read like "what's on the page" rather than "what's in the template
//      source". It does not need sc-for (unused by the pieces under test).
//      Because the template keeps both <sc-if> branches and the class
//      computes both modes' values, techniques 1 and 2 can still render the
//      pre-launch page from the launched build. The "default:" tests that
//      use them are kept for exactly that reason: they are the only place
//      the waitlist state can still be observed from a committed file, and
//      they pin the switch's reversibility (APP_STORE_URL set back to ''
//      must restore the waitlist page, not some third state).
//   3. The mobile drawer is different from techniques 1 and 2: it is static
//      markup baked once per build by build/assemble.py's drawer(), entirely
//      outside index.html's reactive template (no <sc-if>, no renderVals()),
//      so a single committed build can only ever show the branch that was
//      active when it was built. Since launch that is the App Store branch,
//      on index.html and every content page alike, so the live drawer is
//      asserted on the committed pages, and its waitlist branch can only be
//      read from drawer()'s own source text, the same way techniques 1 and
//      2 already treat index.html's source as ground truth for a build.
//      Simulating APP_STORE_URL = '' on the Component cannot un-bake it, so
//      whole-page default assertions exclude it (withoutDrawer() below).
//   4. 2026-09-25 founder follow-up: how-it-works, faq, about, contact,
//      accountability-challenges, the blog hub and both articles each carry
//      their own copy of the same desktop nav pill and closing CTA block as
//      index.html and the drawer (build/assemble.py's
//      apply_content_app_store_switch(), applied to build/content-page.html,
//      build/article-page.html and build/blog-index.html), and four of them
//      also carry their own in-copy waitlist sentence (CONTENT_LIVE_COPY).
//      None of this is reactive, so exactly like technique 3, a committed
//      page carries only the branch its build baked in: since launch, the
//      live one. Those tests read the real committed pages (this build's
//      actual, current state); a second set reads build/assemble.py's
//      source to pin what those pages are generated from.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.join(__dirname, '..');
const APP_STORE_URL = 'https://apps.apple.com/app/id6802558635';

/** Every public page that embeds the shared chrome (drawer, nav pill, closing block). */
const SHARED_CHROME_PAGES = [
  'how-it-works.html', 'faq.html', 'about.html', 'contact.html',
  'accountability-challenges.html', 'blog.html',
  'blog/best-accountability-apps-2026.html', 'blog/why-you-dont-achieve-your-goals.html',
];

/** Escapes a string for safe use inside a RegExp built at runtime. */
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Matches the inline Apple logo mark (a single <path>, aria-hidden, sized in
 * em) shared by the three App Store buttons and the drawer link. Its viewBox
 * is a unique fingerprint on this page: index.html's only other <svg> (a
 * bundler thumbnail template, present regardless of mode) uses
 * viewBox="0 0 100 100".
 */
const APPLE_MARK_RE = /<svg aria-hidden="true" viewBox="0 0 384 512"[^>]*>[\s\S]*?<\/svg>/;

/**
 * Apple's badge as the hero and the closing CTA render it (build/assemble.py's
 * APP_STORE_BADGE_LINK): a plain link to the listing around the unaltered
 * artwork, which is a content-hashed file under /assets/.
 */
const BADGE_LINK_RE = new RegExp(
  `<a href="${escapeRe(APP_STORE_URL)}" data-appstore-badge="" aria-label="Download on the App Store">`
  + '<img src="/assets/app-store-badge-black\\.[0-9a-f]{8}\\.svg" alt="Download on the App Store" width="144" height="48"></a>');

const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// ------------------------------------------------------------- the harness

const scriptMatch = html.match(/<script type="text\/x-dc" data-dc-script[^>]*>([\s\S]*?)<\/script>/);
assert.ok(scriptMatch, 'index.html: could not find the <script type="text/x-dc" data-dc-script> block');
const componentSrc = scriptMatch[1];

class FakeLogic {
  constructor(props) { this.props = props || {}; this.state = {}; }
  setState(update) {
    const patch = typeof update === 'function' ? update(this.state) : update;
    Object.assign(this.state, patch);
  }
  forceUpdate() {}
  componentDidMount() {}
  componentDidUpdate() {}
  componentWillUnmount() {}
  renderVals() { return {}; }
}

// Mirrors assets/app.*.js's evalDcLogic() exactly (same three globals, same
// trailing expression), so this is the real evaluation path, not a guess at it.
const ComponentClass = new Function('DCLogic', 'StreamableLogic', 'React',
  componentSrc + '\n;return (typeof Component!=="undefined"&&Component)||undefined;'
)(FakeLogic, FakeLogic, {});
assert.equal(typeof ComponentClass, 'function', 'index.html: class Component extends DCLogic not found/evaluable');

/** renderVals() for a fresh instance with the given APP_STORE_URL ('' = default/off). */
function valsFor(appStoreUrl) {
  const c = new ComponentClass();
  c.APP_STORE_URL = appStoreUrl;
  return c.renderVals();
}

const DEFAULT_VALS = valsFor('');
const LIVE_VALS = valsFor(APP_STORE_URL);

// ---------------------------------------------------------- template micro-resolver

function resolveExpr(vals, expr) {
  expr = expr.trim();
  if (expr[0] === '!') return !resolveExpr(vals, expr.slice(1));
  if (expr === 'true') return true;
  if (expr === 'false') return false;
  return vals[expr];
}

/** Index of the </sc-if> that matches the <sc-if ...> whose '>' is at openEnd. */
function findMatchingClose(src, openEnd) {
  let depth = 1;
  let i = openEnd;
  for (;;) {
    const nextOpen = src.indexOf('<sc-if', i);
    const nextClose = src.indexOf('</sc-if>', i);
    if (nextClose === -1) throw new Error('unmatched <sc-if> in index.html');
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth++;
      i = src.indexOf('>', nextOpen) + 1;
    } else {
      depth--;
      if (depth === 0) return nextClose;
      i = nextClose + '</sc-if>'.length;
    }
  }
}

/**
 * Resolves {{ expr }} interpolation and nested <sc-if value="{{ expr }}">
 * blocks against `vals`, the same object the real runtime's renderVals()
 * produces. A function-valued expression (an event handler) renders as the
 * literal "fn" marker, present vs. absent being exactly what matters for the
 * plates' onClick/onKeyDown. Good enough for this page's own template
 * (sc-for is not used by anything under test, so it is left unhandled).
 */
function renderTemplate(src, vals) {
  let out = '';
  let i = 0;
  for (;;) {
    const nextTag = src.indexOf('<sc-if', i);
    if (nextTag === -1) { out += src.slice(i); break; }
    out += src.slice(i, nextTag);
    const tagEnd = src.indexOf('>', nextTag) + 1;
    const tagText = src.slice(nextTag, tagEnd);
    const exprMatch = tagText.match(/value="\{\{([^}]+)\}\}"/);
    const closeIdx = findMatchingClose(src, tagEnd);
    const inner = src.slice(tagEnd, closeIdx);
    const keep = exprMatch ? resolveExpr(vals, exprMatch[1]) : false;
    out += keep ? renderTemplate(inner, vals) : '';
    i = closeIdx + '</sc-if>'.length;
  }
  return out.replace(/\{\{\s*([^}]+?)\s*\}\}/g, (_, expr) => {
    const v = resolveExpr(vals, expr);
    if (v === undefined || v === null || v === false) return '';
    if (typeof v === 'function') return 'fn';
    return String(v);
  });
}

// Sanity-check the micro-resolver itself against a case with a known answer,
// before trusting it for the real assertions below.
test('sanity: the template micro-resolver keeps only the true sc-if branch and drops the other', () => {
  const t = '<sc-if value="{{ a }}">YES</sc-if><sc-if value="{{ !a }}">NO</sc-if><p>{{ b }}</p>';
  assert.equal(renderTemplate(t, { a: true, b: 'hi' }), 'YES<p>hi</p>');
  assert.equal(renderTemplate(t, { a: false, b: 'hi' }), 'NO<p>hi</p>');
});

const DEFAULT_HTML = renderTemplate(html, DEFAULT_VALS);
const LIVE_HTML = renderTemplate(html, LIVE_VALS);

/**
 * The Component class's own JS source (inside <script type="text/x-dc"
 * data-dc-script>) necessarily contains both 'JOIN THE WAITLIST' and
 * 'Download app' as string literals: renderVals() has to compute both
 * regardless of which one is live, since which mode is active
 * isn't known until a real instance's APP_STORE_URL is read. Likewise the
 * mobile nav-hide rule in <style> spells out the App Store URL so it can
 * match it without reading the JS constant (its own dedicated test below).
 * Neither is rendered markup, so whole-page "does this text appear on the
 * page" checks scope to everything outside <script>/<style> tags.
 */
function visibleMarkup(rendered) {
  return rendered.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<style[^>]*>[\s\S]*?<\/style>/g, '');
}

const DEFAULT_VISIBLE = visibleMarkup(DEFAULT_HTML);
const LIVE_VISIBLE = visibleMarkup(LIVE_HTML);

/**
 * The shared mobile drawer (#hz-menu) is Python-baked (technique 3): the
 * same bytes in DEFAULT_HTML and LIVE_HTML, and since launch they carry the
 * App Store link. Assertions about what index.html's own reactive template
 * renders in default mode exclude it; the drawer's own tests read it
 * directly. drawer() emits exactly one <nav> and closes with "</nav>\n</div>".
 */
const DRAWER_START = '<div id="hz-menu"';
const DRAWER_END = '</nav>\n</div>';

function drawerBounds(markup) {
  const start = markup.indexOf(DRAWER_START);
  assert.notEqual(start, -1, 'the shared mobile drawer (#hz-menu) was not found');
  assert.equal(markup.indexOf(DRAWER_START, start + 1), -1, 'expected exactly one #hz-menu drawer');
  const end = markup.indexOf(DRAWER_END, start);
  assert.notEqual(end, -1, 'could not find the end of the #hz-menu drawer');
  return [start, end + DRAWER_END.length];
}

/** The drawer's own static markup, exactly as committed. */
function drawerOf(markup) {
  const [start, end] = drawerBounds(markup);
  return markup.slice(start, end);
}

/** Everything but the drawer: the markup index.html's own template controls. */
function withoutDrawer(markup) {
  const [start, end] = drawerBounds(markup);
  return markup.slice(0, start) + markup.slice(end);
}

const DEFAULT_REACTIVE = withoutDrawer(DEFAULT_VISIBLE);
const LIVE_REACTIVE = withoutDrawer(LIVE_VISIBLE);

test('sanity: withoutDrawer() removes exactly the #hz-menu block that drawerOf() returns', () => {
  const d = drawerOf(html);
  assert.ok(d.startsWith(DRAWER_START) && d.endsWith(DRAWER_END));
  assert.match(d, /data-hz-panel/);
  assert.equal((d.match(/<nav /g) || []).length, 1);
  // The element itself is gone; the nav's hamburger button still names it
  // (aria-controls="hz-menu"), which is template markup and rightly stays.
  for (const reactive of [DEFAULT_REACTIVE, LIVE_REACTIVE]) {
    assert.doesNotMatch(reactive, /id="hz-menu"/);
    assert.doesNotMatch(reactive, /data-hz-panel/);
    assert.match(reactive, /aria-controls="hz-menu"/);
  }
});

test('sanity: visibleMarkup strips embedded <script> source (which legitimately carries both modes\' copy as string literals)', () => {
  assert.match(DEFAULT_HTML, /appStoreLabel: 'Download app'/, 'precondition: the class field literal is in the source');
  assert.doesNotMatch(DEFAULT_VISIBLE, /appStoreLabel: 'Download app'/);
  // The one "Download app" left in the default render's visible markup is
  // the drawer's Python-baked link (technique 3), not template output.
  assert.doesNotMatch(DEFAULT_REACTIVE, /Download app/);
  assert.equal((DEFAULT_VISIBLE.match(/Download app/g) || []).length, 1);
});

// ---------------------------------------------------------------- default state

test('default (APP_STORE_URL empty): renderVals() computes exactly today\'s waitlist copy', () => {
  assert.equal(DEFAULT_VALS.appStoreMode, false);
  assert.equal(DEFAULT_VALS.appStoreUrl, '');
  assert.equal(DEFAULT_VALS.heroBtn, 'JOIN THE WAITLIST');
  assert.equal(DEFAULT_VALS.finalBtn, 'JOIN THE WAITLIST');
});

// Launch copy mix (2026-10-09): the Upcoming plates list the Hunts open on
// Discover and link each one to its universal link (test/launch-copy.test.js),
// so the waitlist "interest" pickers they used to be (pick0..pick4 and
// pickkey0..pickkey4 with plateRole/plateTabIndex/pickAria0..4, switched off
// in app-store mode) are retired in both modes rather than merely disabled.
test('both modes: renderVals() carries no interest-picker value, and the Component has no picker code left', () => {
  for (const [name, vals] of [['default', DEFAULT_VALS], ['live', LIVE_VALS]]) {
    for (const key of Object.keys(vals)) {
      assert.doesNotMatch(key, /^(pick|plate)/, `${name}: ${key} should be gone`);
    }
  }
  assert.doesNotMatch(componentSrc, /pickHunt|_picks|_pickKeys|plateRole|pickAria|pickkey/);
  // The interest chip and its clear button stay as inert plumbing.
  assert.equal(typeof DEFAULT_VALS.clearInterest, 'function');
  assert.equal(DEFAULT_VALS.interest, '');
});

test('default: the nav waitlist link is present, targeting #waitlist', () => {
  assert.match(DEFAULT_VISIBLE, /<a href="#waitlist"[^>]*>JOIN THE WAITLIST<\/a>/);
  // Scoped to the reactive template: the Python-baked drawer has read
  // "Download app" in every render since launch (its own tests are below).
  assert.doesNotMatch(DEFAULT_REACTIVE, /Download app/);
});

test('default: the Apple mark SVG renders nowhere in the reactive template', () => {
  assert.doesNotMatch(DEFAULT_REACTIVE, APPLE_MARK_RE);
  assert.doesNotMatch(withoutDrawer(DEFAULT_HTML), APPLE_MARK_RE);
  // The one mark the default render does carry is the drawer's (technique
  // 3), baked in at Python build time, where APP_STORE_URL is set since launch.
  assert.equal((DEFAULT_HTML.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 1);
  assert.match(drawerOf(DEFAULT_HTML), APPLE_MARK_RE);
});

test('default: the hero button is present as a real submit button inside a form, not a link', () => {
  assert.match(DEFAULT_HTML, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('default: the closing CTA is present as a real submit button inside a form, not a link', () => {
  const ctaSection = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="cta"'));
  assert.match(ctaSection, /<form onSubmit="fn"[^>]*>[\s\S]*?<button type="submit"[^>]*>JOIN THE WAITLIST<\/button>/);
});

test('both modes: the Upcoming plates are static cards, one Hunt link each, with no waitlist handler or button role', () => {
  for (const [name, rendered] of [['default', DEFAULT_HTML], ['live', LIVE_HTML]]) {
    const rail = rendered.slice(rendered.indexOf('<div id="ch-rail"'), rendered.indexOf('<section id="why"'));
    const plates = [...rail.matchAll(/<div data-plate=""([^>]*)>/g)];
    assert.equal(plates.length, 3, `${name}: expected the three Hunts open on Discover`);
    for (const [, attrs] of plates) {
      assert.doesNotMatch(attrs, /onClick|onKeyDown|role=|tabIndex|aria-label/, `${name}: a plate still carries picker attributes`);
    }
    assert.equal((rail.match(/<a data-hunt-link="" href="https:\/\/www\.huntz\.ai\/hunt\/[0-9a-f-]{36}"/g) || []).length, 3, `${name}: one Hunt link per plate`);
    assert.doesNotMatch(rail, /Join the waitlist: interested in|\{\{ pick/);
  }
});

test('default: the #waitlist form (Mailchimp endpoint + honeypot) is present exactly once, in the hero', () => {
  assert.equal((DEFAULT_HTML.match(/id="waitlist"/g) || []).length, 1);
  const w = DEFAULT_HTML.slice(DEFAULT_HTML.indexOf('id="waitlist"'));
  assert.match(w.slice(0, w.indexOf('</section>')), /<input type="email"/);
  assert.doesNotMatch(DEFAULT_HTML, /Not on iPhone\? Get notified for Android/);
});

test('default: focusWaitlist and the #waitlist hash handling are present, unconditionally', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

// ------------------------------------------------------------------- live state

test('live (APP_STORE_URL set): renderVals() reports app-store mode', () => {
  assert.equal(LIVE_VALS.appStoreMode, true);
  assert.equal(LIVE_VALS.appStoreUrl, APP_STORE_URL);
  assert.equal(LIVE_VALS.appStoreLabel, 'Download app');
  assert.equal(LIVE_VALS.notifyBtn, 'NOTIFY ME');
});

test('live: the nav link points at the App Store URL and reads "Download app"', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  assert.match(desktopNav, new RegExp(`<a href="${escapeRe(APP_STORE_URL)}"[^>]*>`));
  assert.match(desktopNav, /Download app/);
  assert.doesNotMatch(desktopNav, /JOIN THE WAITLIST/);
  // The mobile hamburger drawer is static markup shared with every other page
  // (build/assemble.py's drawer()), generated once at Python build time from
  // this very same APP_STORE_URL constant rather than by this page's
  // client-side template. Since launch that constant is set, so the drawer
  // carries the App Store link as well and nothing on the live page still
  // reads "JOIN THE WAITLIST"; see the drawer tests near the end of this file.
  assert.equal((LIVE_VISIBLE.match(/JOIN THE WAITLIST/g) || []).length, 0, 'nothing on the live page should still say this');
});

test('live: the hero renders Apple\'s badge as a plain App Store link, not a form', () => {
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  assert.match(heroToPhone, BADGE_LINK_RE);
  assert.doesNotMatch(heroToPhone, /Download app/, 'the pill label is gone from the hero');
  assert.doesNotMatch(heroToPhone, /<form/);
  assert.doesNotMatch(heroToPhone, /NO SPAM/, 'the email-specific "no spam" note should not survive next to a download link');
});

test('live: the closing CTA renders Apple\'s badge as a plain App Store link, not a form', () => {
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf("WHAT'S LIVE"));
  assert.match(ctaSection, BADGE_LINK_RE);
  assert.doesNotMatch(ctaSection, /Download app/, 'the pill label is gone from the closing CTA');
  assert.doesNotMatch(ctaSection, /<form/);
});

test('live: id="fin-form" still exists (the scroll-reveal animation keys off it in both modes)', () => {
  assert.match(LIVE_HTML, /<div id="fin-form"/);
});

test('live: the four App Store links (nav, hero, closing CTA, drawer) share the same URL; the nav and drawer pills read "Download app", the hero and closing carry the badge, and nothing else does', () => {
  const linkRe = new RegExp(`<a href="${escapeRe(APP_STORE_URL)}"`, 'g');
  // Three rendered by the template, plus the Python-baked drawer's own link
  // (technique 3), which this build carries since launch.
  assert.equal((LIVE_REACTIVE.match(linkRe) || []).length, 3, 'expected exactly 3 template-rendered <a> links to the App Store URL (nav, hero, closing CTA)');
  assert.equal((drawerOf(LIVE_VISIBLE).match(linkRe) || []).length, 1, 'expected exactly 1 App Store link in the drawer');
  assert.equal((LIVE_VISIBLE.match(linkRe) || []).length, 4);
  // Our small accent pill: the nav link (template) and the drawer link only.
  assert.equal((LIVE_REACTIVE.match(/Download app/g) || []).length, 1);
  assert.equal((LIVE_VISIBLE.match(/Download app/g) || []).length, 2);
  // Apple's badge: the hero and the closing CTA, one each.
  assert.equal((LIVE_REACTIVE.match(new RegExp(BADGE_LINK_RE.source, 'g')) || []).length, 2);
  assert.equal((LIVE_VISIBLE.match(/data-appstore-badge/g) || []).length, 2);
  // No other spelling of the listing URL anywhere in the visible page.
  assert.equal((LIVE_VISIBLE.match(/apps\.apple\.com/g) || []).length, 4);
});

test('live: the Apple mark SVG renders inside the nav pill before its label, and not in the hero or the closing CTA, which carry Apple\'s own badge', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));
  const heroToPhone = LIVE_HTML.slice(LIVE_HTML.indexOf('<h1'), LIVE_HTML.indexOf('id="hz-phone"'));
  const ctaSection = LIVE_HTML.slice(LIVE_HTML.indexOf('id="fin-form"'), LIVE_HTML.indexOf("WHAT'S LIVE"));

  assert.match(desktopNav, APPLE_MARK_RE, 'nav link: Apple mark SVG missing');
  const markIdx = desktopNav.search(APPLE_MARK_RE);
  const labelIdx = desktopNav.indexOf('Download app');
  assert.notEqual(labelIdx, -1, 'nav link: "Download app" label missing');
  assert.ok(markIdx < labelIdx, 'nav link: the Apple mark should render to the left of the label');
  for (const [name, region] of [['hero', heroToPhone], ['closing CTA', ctaSection]]) {
    assert.doesNotMatch(region, APPLE_MARK_RE, `${name}: our own Apple glyph must not sit next to Apple's badge`);
  }

  // One mark in the template (the nav pill), plus the drawer's own
  // (generated separately at Python build time, technique 3), and nowhere
  // else on the page.
  assert.equal((LIVE_REACTIVE.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 1);
  assert.equal((LIVE_VISIBLE.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 2);
});

// 2026-09-25 founder feedback: the original 0.8em mark read as "super tiny"
// (~10px on the nav pill's 11px font). A fixed size and a wider gap replace
// it; this pins the exact numbers down so a future edit cannot silently
// shrink them back. (The 18px hero and closing marks it also pinned went with
// those pills: the badge's own size is pinned in test/app-store-badge.test.js.)
test('live: the Apple mark is 15px in the nav link, with a 10px gap', () => {
  const desktopNav = LIVE_VISIBLE.slice(LIVE_VISIBLE.indexOf('id="hz-nav"'), LIVE_VISIBLE.indexOf('<section id="hz-hero"'));

  assert.match(desktopNav, /<svg aria-hidden="true" viewBox="0 0 384 512" width="15px" height="15px"/, 'nav mark should be 15px square');
  assert.match(desktopNav, /gap:10px/, 'nav: expected a 10px icon-to-label gap');
});

test('live: the waitlist form survives exactly once, relocated to the bottom and retitled for Android, with the same Mailchimp endpoint', () => {
  assert.equal((LIVE_VISIBLE.match(/id="waitlist"/g) || []).length, 1, 'exactly one #waitlist in the live DOM');
  assert.equal((LIVE_VISIBLE.match(/Not on iPhone\? Get notified for Android/g) || []).length, 1);
  assert.equal((LIVE_VISIBLE.match(/NOTIFY ME/g) || []).length, 1);

  const androidSectionStart = LIVE_VISIBLE.indexOf('Not on iPhone');
  const androidSection = LIVE_VISIBLE.slice(LIVE_VISIBLE.lastIndexOf('<section', androidSectionStart));
  assert.match(androidSection, /id="waitlist"/, 'the relocated section carries the #waitlist id');
  assert.match(androidSection, /<input type="email"/);
  assert.match(androidSection, />NOTIFY ME</);

  // It is physically the last section before the footer.
  const footerIdx = LIVE_VISIBLE.indexOf('<footer');
  assert.ok(androidSectionStart < footerIdx && footerIdx - androidSectionStart < 2000,
    'the Android waitlist section should sit immediately before the footer');

  // Same backend as before: no second Mailchimp integration was introduced.
  // (The generic "list-manage.com/subscribe/post?u=..." pattern also matches
  // the WAITLIST_ENDPOINT doc comment above the field, so this checks the
  // real, fully-qualified audience endpoint specifically: the same string
  // build/check.py's MC_ENDPOINT check uses.)
  assert.equal((html.match(/huntz\.us18\.list-manage\.com\/subscribe\/post/g) || []).length, 1);
  assert.match(html, /WAITLIST_HONEYPOT = 'b_b7144d02c740628b3280ff55f_3ee28a30af'/);
});

test('live: focusWaitlist and the #waitlist hash handling are untouched and still generic (getElementById, no mode branching)', () => {
  assert.match(html, /function focusWaitlist\(\)/);
  assert.match(html, /var w = document\.getElementById\('waitlist'\)/);
  assert.match(html, /location\.hash === '#waitlist'/);
});

test('live: the mobile nav-hide rule hides the App Store link too, without reading the JS constant', () => {
  assert.match(html, /a\[href="#waitlist"\],#hz-nav a\[href="https:\/\/apps\.apple\.com\/app\/id6802558635"\]\{display:none !important\}/);
});

// ---------------------------------------------- the shared drawer (technique 3)

// build/assemble.py's drawer() is called for every page (index.html and every
// content page) and bakes its waitlist/App Store link once, at Python build
// time, from the module-level APP_STORE_URL constant -- see this file's own
// header comment above. Since launch every committed page carries its App
// Store branch, asserted on the real markup first; the waitlist branch can
// only be read from the function's own source text, the same way techniques
// 1 and 2 above trust index.html's source as ground truth.
const DRAWER_LIVE_LINK_RE = new RegExp(
  `<a href="${escapeRe(APP_STORE_URL)}" style="display:flex;align-items:center;justify-content:center;gap:10px;min-height:52px;margin-top:20px;[^"]*">`
  + '<svg aria-hidden="true" viewBox="0 0 384 512" width="18px" height="18px"[^>]*>[\\s\\S]*?<\\/svg><span>Download app<\\/span><\\/a>');

test('live: the committed drawer on index.html and every content page links to the App Store with the 18px Apple mark and reads "Download app", with no waitlist link left', () => {
  for (const rel of ['index.html', ...SHARED_CHROME_PAGES]) {
    const d = drawerOf(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
    assert.match(d, DRAWER_LIVE_LINK_RE, `${rel}: drawer App Store link missing or changed`);
    assert.equal((d.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 1, `${rel}: expected exactly one Apple mark in the drawer`);
    assert.equal((d.match(/Download app/g) || []).length, 1, `${rel}: expected exactly one "Download app" in the drawer`);
    assert.doesNotMatch(d, /JOIN THE WAITLIST/, `${rel}: the drawer still offers the waitlist`);
    assert.doesNotMatch(d, /#waitlist/, `${rel}: the drawer still links to #waitlist`);
  }
});

const assemblePy = fs.readFileSync(path.join(ROOT, 'build', 'assemble.py'), 'utf8');
const drawerStart = assemblePy.indexOf('def drawer(');
const drawerEnd = assemblePy.indexOf('def footer_nav(');
assert.ok(drawerStart !== -1 && drawerEnd !== -1 && drawerStart < drawerEnd,
  'build/assemble.py: could not isolate the drawer() function source');
const drawerSrc = assemblePy.slice(drawerStart, drawerEnd);

test('live: build/assemble.py\'s drawer() carries the Apple mark and reads "Download app" once APP_STORE_URL is set', () => {
  assert.match(drawerSrc, /if APP_STORE_URL and app_store:/,
    'drawer() has no APP_STORE_URL conditional (guarded by its own app_store opt-out)');
  const liveBranch = drawerSrc.slice(drawerSrc.indexOf('if APP_STORE_URL and app_store:'), drawerSrc.indexOf('else:'));
  assert.match(liveBranch, /apple_mark\(18\)/, 'drawer() live branch should use the shared 18px Apple mark');
  assert.match(liveBranch, /gap:10px/, 'drawer() live branch should use a 10px icon-to-label gap');
  assert.match(liveBranch, /Download app/, 'drawer() live branch does not read "Download app"');
  assert.match(liveBranch, /href="\{APP_STORE_URL\}"/, 'drawer() live branch does not link to APP_STORE_URL');
  assert.doesNotMatch(liveBranch, /JOIN THE WAITLIST/);
});

// auth/callback.html (account-agnostic, no App Store claims) embeds this same
// shared drawer but must never show the App Store link, regardless of the
// site-wide switch: its own build/check.py rule forbids it outright. With
// APP_STORE_URL live, a regression here is visible on the committed page
// itself, so both the call site and its output are checked. (The /hunt
// fallback opted out the same way until launch day; see its own test in the
// launch-leftovers section below.)
test('drawer() call site: auth/callback.html opts out of the App Store link (app_store=False)', () => {
  assert.match(assemblePy, /drawer\("\/auth\/callback",\s*"[^"]*",\s*app_store=False\)/,
    'build/assemble.py: drawer("/auth/callback", ...) should pass app_store=False');
  const t = fs.readFileSync(path.join(ROOT, 'auth/callback.html'), 'utf8');
  const d = drawerOf(t);
  assert.match(d, /<a href="\/#waitlist"[^>]*>JOIN THE WAITLIST<\/a>/, 'drawer waitlist link missing');
  assert.doesNotMatch(d, /Download app/, 'drawer claims App Store availability');
  assert.doesNotMatch(t, /apps\.apple\.com/, 'App Store URL leaked in');
  assert.doesNotMatch(t, APPLE_MARK_RE, 'Apple mark leaked in');
  // Its own copy never claims the app is unavailable either: every branch
  // sends the reader to the app they already have.
  for (const stale of [/limited beta/i, /publicly available/i, /coming soon/i, /not yet available/i]) {
    assert.doesNotMatch(t, stale, `auth/callback.html says ${stale}`);
  }
});

// With the shared switch on, only the opt-out page above still renders this
// branch; its source is pinned here so it stays exactly as it was.
test('default: build/assemble.py\'s drawer() default branch stays plain "JOIN THE WAITLIST" with no Apple mark', () => {
  assert.match(drawerSrc, /\belse:/, 'drawer() has no default-branch else clause');
  // Sliced up to the function's own return statement, not to the end of
  // drawerSrc, so this does not spill into unrelated markup below (e.g. the
  // header row's own "gap:14px") that has nothing to do with this branch.
  const defaultBranch = drawerSrc.slice(drawerSrc.indexOf('else:'), drawerSrc.indexOf('return f"""'));
  assert.match(defaultBranch, /href="\{waitlist_href\}"/, 'default branch does not link to waitlist_href');
  assert.match(defaultBranch, />JOIN THE WAITLIST<\/a>/);
  assert.doesNotMatch(defaultBranch, /apple_mark\(/);
  assert.doesNotMatch(defaultBranch, /Download app/);
  // No icon means no icon-to-label gap: the exact same style this branch
  // has always had, with nothing added for this feature.
  assert.doesNotMatch(defaultBranch, /gap:/);
});

// ------------------------------------------ content pages + blog (technique 4)

// The launched build: every content page's shared chrome is in App Store
// mode (build/assemble.py's NAV_PILL_LIVE and CLOSING_BLOCK_LIVE, applied by
// apply_content_app_store_switch()), read here from the committed pages.
const NAV_PILL_LIVE_RE = new RegExp(
  `<a data-hz-desknav href="${escapeRe(APP_STORE_URL)}" style="display:inline-flex;align-items:center;gap:10px;border-radius:999px;font:700 11px[^>]*>`
  + '<svg aria-hidden="true" viewBox="0 0 384 512" width="15px" height="15px"[^>]*>[\\s\\S]*?<\\/svg><span>Download app<\\/span><\\/a>');
const CLOSING_CTA_LIVE_RE = new RegExp(
  `<a href="${escapeRe(APP_STORE_URL)}" style="display:inline-flex;align-items:center;gap:10px;flex:0 0 auto;border-radius:999px;[^>]*>`
  + '<svg aria-hidden="true" viewBox="0 0 384 512" width="18px" height="18px"[^>]*>[\\s\\S]*?<\\/svg><span>Download app<\\/span><\\/a>');
const ANDROID_LINK_RE = /<a href="\/#waitlist" style="font:600 11px[^>]*>Not on iPhone\? Get notified for Android\.<\/a>/;

for (const rel of SHARED_CHROME_PAGES) {
  test(`live: ${rel} carries the shared App Store nav pill and closing block, and no waitlist chrome`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.match(t, NAV_PILL_LIVE_RE, 'desktop nav pill missing or changed');
    assert.match(t, /Huntz is on the App Store<span style="color:#C24E1F">\.<\/span>/, 'closing heading missing or changed');
    assert.match(t, CLOSING_CTA_LIVE_RE, 'closing button missing or changed');
    // The Android fallback (the home page's relocated form) is the only
    // thing left pointing at the waitlist, under the heading and ahead of
    // the store button.
    assert.match(t, ANDROID_LINK_RE, 'Android fallback link missing or changed');
    assert.equal((t.match(/href="\/#waitlist"/g) || []).length, 1, 'expected the Android fallback to be the only /#waitlist link');
    assert.ok(t.search(ANDROID_LINK_RE) < t.search(CLOSING_CTA_LIVE_RE), 'the Android link should come before the store button');
    // Pre-launch chrome is gone entirely.
    assert.doesNotMatch(t, /JOIN THE WAITLIST/);
    assert.doesNotMatch(t, /Ready when you are/);
    assert.doesNotMatch(t, /Join the waitlist and we'll email you when the first Hunts open\./);
    // Nav pill, closing button and drawer: exactly three store links, three
    // labels and three marks per page, so nothing else claims the listing.
    assert.equal((t.match(/Download app/g) || []).length, 3);
    assert.equal((t.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 3);
  });
}

// Each of these pages also carries its own in-copy sentence or meta
// description (build/pages/<slug>.json, rewritten at build time by
// CONTENT_LIVE_COPY), separate from the shared chrome above. The pre-launch
// wording is asserted gone as well, so a page cannot carry both.
test('live: about.html\'s in-copy sentence points at the app, and its meta description says it is available', () => {
  const t = fs.readFileSync(path.join(ROOT, 'about.html'), 'utf8');
  assert.match(t, new RegExp(`Self-service tools for creators to launch Hunts independently are planned for later\\. The <a href="${escapeRe(APP_STORE_URL)}"[^>]*>app</a> is the way in\\.`));
  assert.doesNotMatch(t, /waitlist<\/a> is the way in\./);
  assert.match(t, /<meta name="description" content="[^"]*Built in Oakland by Huntz, Inc\. Available now on the App Store\.">/);
  assert.doesNotMatch(t, /Pre-launch, waitlist open/);
});

test('live: faq.html\'s "Is Huntz available right now?" answer says "Yes." with a download link, and its meta description drops "waitlist"', () => {
  const t = fs.readFileSync(path.join(ROOT, 'faq.html'), 'utf8');
  assert.match(t, new RegExp(`Yes\\. Huntz is live on the App Store, with the first Hunts developed directly with our first creators\\. <a href="${escapeRe(APP_STORE_URL)}"[^>]*>Download the app</a> to join one\\. Huntz is for adults 18 and up\\.`));
  assert.doesNotMatch(t, /Not yet\. The first Hunts are being developed now/);
  assert.match(t, /<meta name="description" content="[^"]*Huntz is live: the iOS app is available now on the App Store\.">/);
  assert.doesNotMatch(t, /waitlist at huntz\.ai is open/);
});

test('live: how-it-works.html\'s in-copy sentence says the first Hunts are live in the app', () => {
  const t = fs.readFileSync(path.join(ROOT, 'how-it-works.html'), 'utf8');
  assert.match(t, new RegExp(`The first Hunts are live in <a href="${escapeRe(APP_STORE_URL)}"[^>]*>the app</a>\\.</p>`));
  assert.doesNotMatch(t, /Join the waitlist<\/a> and we will email you when they open\./);
});

test('live: contact.html\'s troubleshooting bullet and meta description say "the app", not "the waitlist"', () => {
  const t = fs.readFileSync(path.join(ROOT, 'contact.html'), 'utf8');
  assert.match(t, /Problems with the app or this website: tell us what broke and on what device\./);
  assert.doesNotMatch(t, /Problems with the waitlist or this website/);
  assert.match(t, /<meta name="description" content="Reach the Huntz team\. Questions about accountability challenges, the app, privacy, or partnerships: team@huntz\.ai\. Based in Oakland, California\.">/);
});

test('live: accountability-challenges.html\'s meta description says the app is available', () => {
  const t = fs.readFileSync(path.join(ROOT, 'accountability-challenges.html'), 'utf8');
  assert.match(t, /<meta name="description" content="[^"]*stakes and published rules\. Available now on the App Store\.">/);
  assert.doesNotMatch(t, /Pre-launch; iOS waitlist open/);
});

// The explicit byte-for-byte guarantee, pinned as a hash rather than a huge
// inline literal: the committed about.html is the launched page, so any
// change at all to it, however small (a rebuild with the switch flipped
// back, a drifted shell template), fails here rather than only in the
// broader checks above. Update the pin deliberately when the page changes
// on purpose.
test('live: about.html is byte-for-byte the committed launched page (sha256 pin)', () => {
  const bytes = fs.readFileSync(path.join(ROOT, 'about.html'));
  const hash = crypto.createHash('sha256').update(bytes).digest('hex');
  assert.equal(hash, '29c69a6263c1de390c935c60e8d475e3049f454bfc153c44b82d15b5d46c93ed',
    'about.html changed: the launched (APP_STORE_URL set) state must stay byte-for-byte identical to the committed page');
});

// ---- live state as build/assemble.py's source generates it: the committed
// pages above are its output, these pin the input (see the header comment
// above) ----

// Sliced up to the next comment/assignment, not all the way to the next
// constant, so neither slice picks up build/assemble.py's own prose (which
// legitimately says "waitlist" while explaining the switch).
const navPillLiveSrc = assemblePy.slice(assemblePy.indexOf('NAV_PILL_LIVE = ('),
  assemblePy.indexOf("# The heading's own margin-bottom"));
const closingBlockLiveSrc = assemblePy.slice(assemblePy.indexOf('CLOSING_BLOCK_LIVE = ('), assemblePy.indexOf('def apply_content_app_store_switch'));

test('live: build/assemble.py\'s NAV_PILL_LIVE carries the 15px Apple mark, "Download app", a pill radius and the App Store href', () => {
  assert.match(navPillLiveSrc, /apple_mark\(15\)/);
  assert.match(navPillLiveSrc, /Download app/);
  assert.match(navPillLiveSrc, /href="\{APP_STORE_URL\}"/);
  assert.match(navPillLiveSrc, /border-radius:999px/);
  assert.doesNotMatch(navPillLiveSrc, /JOIN THE WAITLIST/);
});

test('live: build/assemble.py\'s CLOSING_BLOCK_LIVE reads "Huntz is on the App Store.", carries the 18px mark, and no longer buttons to /#waitlist', () => {
  assert.match(closingBlockLiveSrc, /Huntz is on the App Store/);
  assert.match(closingBlockLiveSrc, /apple_mark\(18\)/);
  assert.match(closingBlockLiveSrc, /Download app/);
  assert.match(closingBlockLiveSrc, /href="\{APP_STORE_URL\}"/);
  // The main CTA button no longer points at /#waitlist; only the small
  // Android fallback link below it does. Sliced up to that link's own
  // wrapper div, i.e. before its href, not up to its inner text.
  const ctaOnly = closingBlockLiveSrc.slice(0, closingBlockLiveSrc.indexOf('margin-top:14px'));
  assert.doesNotMatch(ctaOnly, /href="\/#waitlist"/, 'the main CTA button should not still point at #waitlist');
  // Two separate checks, not one spanning regex: build/assemble.py wraps
  // this string across several Python literals, so the raw source has a
  // quote/newline seam between the style attribute and the link text.
  assert.match(closingBlockLiveSrc, /href="\/#waitlist" style="font:600 11px/);
  assert.match(closingBlockLiveSrc, /Not on iPhone\? Get notified for Android\.<\/a><\/div>/);
});

test('live: no leftover "waitlist" wording in NAV_PILL_LIVE or CLOSING_BLOCK_LIVE, except the Android link\'s href', () => {
  for (const [name, src] of [['NAV_PILL_LIVE', navPillLiveSrc], ['CLOSING_BLOCK_LIVE', closingBlockLiveSrc]]) {
    const withoutAndroidHref = src.split('href="/#waitlist"').join('');
    assert.doesNotMatch(withoutAndroidHref, /waitlist/i, `${name}: unexpected leftover "waitlist" wording`);
  }
});

test('live: apply_content_app_store_switch() is wired to all three page shells (content, article, blog hub)', () => {
  for (const tplFile of ['content-page.html', 'article-page.html', 'blog-index.html']) {
    const pattern = new RegExp(`apply_content_app_store_switch\\(\\(BUILD / "${escapeRe(tplFile)}"\\)\\.read_text\\(\\)\\)`);
    assert.match(assemblePy, pattern, `build/assemble.py: ${tplFile} is not wrapped in apply_content_app_store_switch()`);
  }
});

test('live: about.json gets a launch-state in-copy sentence and meta description', () => {
  assert.match(assemblePy, />app<\/a> is the way in\.<\/p>/, 'about: expected "...the app is the way in." sentence not found');
  assert.match(assemblePy, /Built in Oakland by Huntz, Inc\. Available now on the App Store\./);
});

test('live: accountability-challenges.json gets a launch-state meta description', () => {
  assert.match(assemblePy, /stakes and published rules\. Available now on the App Store\./);
});

test('live: contact.json gets a launch-state meta description and troubleshooting bullet', () => {
  assert.match(assemblePy, /Questions about accountability challenges, the app, privacy, or partnerships:/);
  assert.match(assemblePy, /Problems with the app or this website:/);
});

test('live: faq.json\'s "Is Huntz available right now?" answer becomes "Yes." with a download link, and the meta description drops "waitlist"', () => {
  assert.match(assemblePy, /Huntz is live: the iOS app is available/);
  assert.match(assemblePy, /Yes\. Huntz is live on the App Store, with the first Hunts developed directly with/);
  assert.match(assemblePy, />Download the app<\/a> to join one\./);
});

test('live: how-it-works.json\'s in-copy sentence becomes "The first Hunts are live in the app."', () => {
  assert.match(assemblePy, /The first Hunts are live in /);
  assert.match(assemblePy, />the app<\/a>\.<\/p>/);
});

// ------------------------------- the "What's live" card ((S-2b), launch day)

// The home page's closing card is static markup patched at Python build time
// (build/assemble.py's (S-2b) block), not reactive, so like the drawer it
// reads the same in both renders and is asserted on the committed page. The
// launch copy mix (2026-10-09) retitled it from "What happens next" to
// "What's live": the iOS app is ON THE APP STORE, creator-hosted and private
// Hunts are LIVE, and the Android app is the one row still COMING SOON, last
// and without the rule the other rows carry. The switch-off card can only be
// read from the source.
const NEXT_ROW_RE = (label, pill, last = false) => new RegExp(
  '<div style="display:flex;justify-content:space-between;align-items:baseline;gap:12px;padding:11px 0'
  + (last ? '' : ';border-bottom:1px solid rgba\\(22,19,14,\\.1\\)') + '">'
  + `<span style="[^"]*">${escapeRe(label)}</span><span style="[^"]*">${escapeRe(pill)}</span></div>`);

test('live: the "What\'s live" card lists the iOS app, creator-hosted hunts and private hunts as live, then the Android app as COMING SOON', () => {
  const start = html.indexOf("WHAT'S LIVE");
  assert.notEqual(start, -1, 'the "What\'s live" card was not found');
  assert.doesNotMatch(html, /WHAT HAPPENS NEXT/, 'the pre-launch title should be gone');
  const card = html.slice(start, html.indexOf('</section>', start));
  const rows = [
    card.search(NEXT_ROW_RE('iOS app', 'ON THE APP STORE')),
    card.search(NEXT_ROW_RE('Creator-hosted hunts', 'LIVE')),
    card.search(NEXT_ROW_RE('Private hunts with friends', 'LIVE')),
    card.search(NEXT_ROW_RE('Android app', 'COMING SOON', true)),
  ];
  rows.forEach((at, i) => assert.notEqual(at, -1, `row ${i} missing or changed`));
  assert.deepEqual([...rows].sort((a, b) => a - b), rows, 'the three live rows come first, Android last');
  assert.equal((card.match(/ON THE APP STORE/g) || []).length, 1);
  assert.equal((card.match(/>LIVE</g) || []).length, 2);
  assert.equal((card.match(/COMING SOON/g) || []).length, 1, 'only the Android app is still to come');
  // LIVE wears the same accent pill as the other two labels: one style string for all four.
  const pills = [...card.matchAll(/<span style="(font:700 8\.5px[^"]*)">(ON THE APP STORE|LIVE|COMING SOON)<\/span>/g)];
  assert.equal(pills.length, 4);
  assert.equal(new Set(pills.map((p) => p[1])).size, 1, 'all four pills share one style');
  assert.match(pills[0][1], /color:#C24E1F/);
  assert.doesNotMatch(html, /iOS &amp; Android app/, 'the pre-launch combined row should be gone');
});

test('default: build/assemble.py keeps the single "iOS & Android app / COMING SOON" row while APP_STORE_URL is empty', () => {
  const s2b = assemblePy.slice(assemblePy.indexOf('# (S-2b)'), assemblePy.indexOf('# (AS-1)'));
  assert.ok(s2b.length > 0, 'build/assemble.py: could not isolate the (S-2b) block');
  assert.match(s2b, /iOS &amp; Android app<\/span>'\n\s*f'<span \{ROW_PILL\}>COMING SOON<\/span><\/div>'\)/);
  assert.match(s2b, /\nassert old in html/, 'the pre-launch row is asserted present in the template regardless of mode');
  assert.match(s2b, /\nif APP_STORE_URL:\n\s+html = html\.replace\(old,/, 'the split is gated on the switch');
});

// ------------------------------------------- launch leftovers (2026-10-09)

// The statements the launch switch did not reach on its own, each fixed in
// build/assemble.py (HEAD_META, CONTENT_LIVE_COPY) the day the app went live.

test('live: the home meta description says Huntz is on the App Store, in under 160 characters', () => {
  const m = html.match(/<meta name="description" content="([^"]*)">/);
  assert.ok(m, 'home meta description missing');
  assert.match(m[1], /Huntz is on the App Store\.$/);
  assert.doesNotMatch(m[1], /pre-launch/i);
  assert.ok(m[1].length < 160, `home meta description is ${m[1].length} chars`);
});

test('live: how-it-works.html\'s meta description drops "Pre-launch"', () => {
  const t = fs.readFileSync(path.join(ROOT, 'how-it-works.html'), 'utf8');
  assert.match(t, /<meta name="description" content="How a Hunt works: rules published before anyone joins, a committed stake, proof on a schedule, finishers recover their stake plus forfeit shares\.">/);
  assert.doesNotMatch(t, /Pre-launch/);
});

test('live: about.html says Huntz is live on the App Store, in step with faq.html', () => {
  const t = fs.readFileSync(path.join(ROOT, 'about.html'), 'utf8');
  assert.match(t, /Huntz is live on the App Store, with the first Hunts developed directly with selected creators for their communities\. Self-service tools/);
  assert.doesNotMatch(t, /being developed now/);
});

test('live: the Android notify section names the Android launch, and nothing visible on the live page still says WHEN WE LAUNCH', () => {
  // The no-spam line is always rendered; the confirmation stamp sits behind
  // sc-if sub1 (a fresh page has not submitted), so it is read from the
  // section's own source.
  assert.equal((LIVE_VISIBLE.match(/WHEN ANDROID LAUNCHES/g) || []).length, 1, 'the no-spam line');
  const sectionStart = html.indexOf('data-screen-label="Android Waitlist"');
  assert.notEqual(sectionStart, -1, 'the Android section was not found');
  const section = html.slice(sectionStart, html.indexOf('</section>', sectionStart));
  assert.equal((section.match(/WHEN ANDROID LAUNCHES/g) || []).length, 2, 'the confirmation stamp and the no-spam line');
  assert.doesNotMatch(section, /WHEN WE LAUNCH/);
  assert.doesNotMatch(LIVE_VISIBLE, /WHEN WE LAUNCH/);
  // The switched-off hero keeps its own wording: there "we" is unambiguous.
  assert.match(DEFAULT_REACTIVE, /WHEN WE LAUNCH/);
  assert.doesNotMatch(DEFAULT_REACTIVE, /WHEN ANDROID LAUNCHES/);
});

test('the hero eyebrow separates HUNTZ from the brand line with a colon, and no em dash is left in the home page\'s visible markup', () => {
  assert.match(LIVE_VISIBLE, />HUNTZ: THE MARKETPLACE FOR ACCOUNTABILITY</);
  assert.doesNotMatch(LIVE_VISIBLE, /HUNTZ — THE MARKETPLACE/);
  assert.doesNotMatch(visibleMarkup(html), /—/);
});

// The /hunt invitation fallback used to opt out of the switch too ("limited
// beta", join the waitlist). Since launch day it is the launched page: the
// shared drawer link, the shared nav pill and its own store button all send
// the recipient to the listing, and no pre-launch copy is left anywhere in
// the served bytes. build/check.py enforces the same, deliberately inverted
// from its pre-launch rule.
const HUNT_STORE_BTN_RE = new RegExp(
  `<a href="${escapeRe(APP_STORE_URL)}" style="display:inline-flex;align-items:center;gap:10px;margin-top:22px;border-radius:999px;[^>]*>`
  + '<svg aria-hidden="true" viewBox="0 0 384 512" width="18px" height="18px"[^>]*>[\\s\\S]*?<\\/svg><span>Get Huntz on the App Store<\\/span><\\/a>');

test('live: api/_lib/hunt-fallback.html sends the recipient to the App Store (drawer, nav pill and its own button) with no pre-launch copy left', () => {
  assert.match(assemblePy, /drawer\("\/hunt",\s*"[^"]*"\)/, 'build/assemble.py: drawer("/hunt", ...) should follow the shared switch');
  const t = fs.readFileSync(path.join(ROOT, 'api/_lib/hunt-fallback.html'), 'utf8');
  assert.match(drawerOf(t), DRAWER_LIVE_LINK_RE, 'drawer App Store link missing or changed');
  assert.match(t, NAV_PILL_LIVE_RE, 'desktop nav pill missing or changed');
  assert.match(t, HUNT_STORE_BTN_RE, 'store button missing or changed');
  assert.equal((t.match(new RegExp(escapeRe(APP_STORE_URL), 'g')) || []).length, 3, 'nav pill, drawer and the button: exactly three store links');
  assert.equal((t.match(new RegExp(APPLE_MARK_RE.source, 'g')) || []).length, 3);
  assert.match(t, /open the original invitation again/, 'the reopen instruction must survive');
  assert.match(t, /<meta name="description" content="This Hunt invitation opens in the Huntz app\. Get Huntz on the App Store, then open your invitation again on your iPhone to see the Hunt and join\.">/);
  for (const stale of [/limited beta/i, /waitlist/i, /publicly available/i, /TestFlight/i, /&#8212;/, /—/]) {
    assert.doesNotMatch(t, stale, `hunt-fallback.html still carries ${stale}`);
  }
  // The last-resort copy embedded in api/hunt.js says the same thing.
  const js = fs.readFileSync(path.join(ROOT, 'api/hunt.js'), 'utf8');
  assert.doesNotMatch(js, /limited beta/i);
  assert.doesNotMatch(js, /waitlist/i);
  assert.match(js, /Get Huntz on the App Store/);
});

// -------------------------------------------------------------- meta tag

const APPLE_ITUNES_META = '<meta name="apple-itunes-app" content="app-id=6802558635">';

const PUBLIC_PAGES = [
  'index.html', 'how-it-works.html', 'faq.html', 'about.html', 'contact.html',
  'accountability-challenges.html', 'blog.html',
  'blog/best-accountability-apps-2026.html', 'blog/why-you-dont-achieve-your-goals.html',
  'terms.html', 'privacy.html',
];

for (const rel of PUBLIC_PAGES) {
  test(`Smart App Banner meta tag is present in the <head> of ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.ok(t.indexOf(APPLE_ITUNES_META) > 0, `${rel}: missing ${APPLE_ITUNES_META}`);
    assert.ok(t.indexOf(APPLE_ITUNES_META) < t.indexOf('</head>'), `${rel}: meta tag is outside <head>`);
  });
}

const UTILITY_PAGES = [
  'auth/callback.html',
  'mailbox/gmail-action/pair.html',
  'payouts/return.html',
  'payouts/refresh.html',
];

for (const rel of UTILITY_PAGES) {
  test(`Smart App Banner meta tag is absent from the noindex utility page ${rel}`, () => {
    const t = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    assert.doesNotMatch(t, /apple-itunes-app/, `${rel}: should not carry the Smart App Banner`);
    // These are exactly the "noindex utility" pages this feature must skip.
    assert.match(t, /name="robots" content="noindex/, `${rel}: expected to be a noindex page`);
  });
}
